package setting;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class DlgSetAturanPasswordSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();

    public DlgSetAturanPasswordSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {
            "Min. Karakter", "Huruf Besar", "Huruf Kecil", "Angka", "Simbol", "Ingatkan Setiap (Hari)"
        }) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };

        tbAturan.setModel(tabMode);
        tbAturan.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbAturan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i < tabMode.getColumnCount(); i++) {
            tbAturan.getColumnModel().getColumn(i).setPreferredWidth(i == 5 ? 130 : 90);
        }
        tbAturan.setDefaultRenderer(Object.class, new WarnaTable());

        PanjangMinimal.setDocument(new batasInput((byte) 3).getOnlyAngka(PanjangMinimal));
        HariPeringatan.setDocument(new batasInput((byte) 4).getOnlyAngka(HariPeringatan));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbAturan = new widget.Table();
        panelGlass5 = new widget.panelisi();
        jLabel3 = new widget.Label();
        PanjangMinimal = new widget.TextBox();
        jLabel4 = new widget.Label();
        jLabel5 = new widget.Label();
        HurufBesar = new widget.CekBox();
        HurufKecil = new widget.CekBox();
        Angka = new widget.CekBox();
        Simbol = new widget.CekBox();
        jLabel6 = new widget.Label();
        HariPeringatan = new widget.TextBox();
        jLabel7 = new widget.Label();
        panelGlass6 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Aturan Password ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbAturan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbAturan.setName("tbAturan"); // NOI18N
        tbAturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAturanMouseClicked(evt);
            }
        });
        tbAturan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbAturanKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbAturan);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 103));
        panelGlass5.setLayout(null);

        jLabel3.setText("Min. Karakter :");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass5.add(jLabel3);
        jLabel3.setBounds(0, 10, 115, 23);

        PanjangMinimal.setToolTipText("Jumlah karakter minimal password, kosongkan jika tidak dibatasi");
        PanjangMinimal.setName("PanjangMinimal"); // NOI18N
        PanjangMinimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanjangMinimalKeyPressed(evt);
            }
        });
        panelGlass5.add(PanjangMinimal);
        PanjangMinimal.setBounds(118, 10, 50, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("karakter");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass5.add(jLabel4);
        jLabel4.setBounds(171, 10, 60, 23);

        jLabel5.setText("Wajib Mengandung :");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass5.add(jLabel5);
        jLabel5.setBounds(0, 40, 115, 23);

        HurufBesar.setText("Huruf Besar (A-Z)");
        HurufBesar.setName("HurufBesar"); // NOI18N
        panelGlass5.add(HurufBesar);
        HurufBesar.setBounds(118, 40, 120, 23);

        HurufKecil.setText("Huruf Kecil (a-z)");
        HurufKecil.setName("HurufKecil"); // NOI18N
        panelGlass5.add(HurufKecil);
        HurufKecil.setBounds(241, 40, 115, 23);

        Angka.setText("Angka (0-9)");
        Angka.setName("Angka"); // NOI18N
        panelGlass5.add(Angka);
        Angka.setBounds(359, 40, 90, 23);

        Simbol.setText("Simbol (!@#$...)");
        Simbol.setName("Simbol"); // NOI18N
        panelGlass5.add(Simbol);
        Simbol.setBounds(452, 40, 115, 23);

        jLabel6.setText("Ingatkan Ubah Setiap :");
        jLabel6.setName("jLabel6"); // NOI18N
        panelGlass5.add(jLabel6);
        jLabel6.setBounds(0, 70, 115, 23);

        HariPeringatan.setToolTipText("Jumlah hari sejak password terakhir diubah sebelum user diingatkan saat login, kosongkan untuk menonaktifkan");
        HariPeringatan.setName("HariPeringatan"); // NOI18N
        HariPeringatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HariPeringatanKeyPressed(evt);
            }
        });
        panelGlass5.add(HariPeringatan);
        HariPeringatan.setBounds(118, 70, 50, 23);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("hari sejak password terakhir diubah");
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass5.add(jLabel7);
        jLabel7.setBounds(171, 70, 200, 23);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_START);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnHapus);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
        if (tabMode.getRowCount() > 0) {
            tbAturan.setRowSelectionInterval(0, 0);
            getData();
        }
    }//GEN-LAST:event_formWindowOpened

    private void tbAturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAturanMouseClicked
        getData();
    }//GEN-LAST:event_tbAturanMouseClicked

    private void tbAturanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbAturanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            getData();
        }
    }//GEN-LAST:event_tbAturanKeyPressed

    private void PanjangMinimalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanjangMinimalKeyPressed
        Valid.pindah(evt, HariPeringatan, HurufBesar);
    }//GEN-LAST:event_PanjangMinimalKeyPressed

    private void HariPeringatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HariPeringatanKeyPressed
        Valid.pindah(evt, PanjangMinimal, BtnSimpan);
    }//GEN-LAST:event_HariPeringatanKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (!PanjangMinimal.getText().isBlank() && Integer.parseInt(PanjangMinimal.getText()) > 100) {
            JOptionPane.showMessageDialog(null, "Maaf, minimal karakter password tidak boleh lebih dari 100..!!");
            PanjangMinimal.requestFocus();
        } else {
            boolean sukses = false;
            Sequel.AutoComitFalse();
            try {
                Sequel.menghapustfSmc("set_aturan_password_smc");
                sukses = Sequel.menyimpantfSmc("set_aturan_password_smc", "panjang_minimal, huruf_besar, huruf_kecil, angka, simbol, hari_peringatan",
                    PanjangMinimal.getText().isBlank() ? "0" : PanjangMinimal.getText(), HurufBesar.isSelected() ? "Yes" : "No", HurufKecil.isSelected() ? "Yes" : "No",
                    Angka.isSelected() ? "Yes" : "No", Simbol.isSelected() ? "Yes" : "No", HariPeringatan.getText().isBlank() ? "0" : HariPeringatan.getText()
                );
            } catch (Exception e) {
                System.out.println("Notif : " + e);
                sukses = false;
            }

            if (sukses) {
                Sequel.Commit();
            } else {
                Sequel.RollBack();
            }
            Sequel.AutoComitTrue();

            if (sukses) {
                tampil();
                JOptionPane.showMessageDialog(null, "Pengaturan berhasil disimpan..!!");
            } else {
                JOptionPane.showMessageDialog(null, "Pengaturan gagal disimpan..!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis...!!!!");
        } else if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "Hapus aturan password? Password baru tidak akan dibatasi dan user tidak akan diingatkan untuk mengubah password.", "Konfirmasi", JOptionPane.YES_NO_OPTION)) {
            if (Sequel.menghapustfSmc("set_aturan_password_smc")) {
                tampil();
                emptTeks();
            }
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSetAturanPasswordSMC dialog = new DlgSetAturanPasswordSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox Angka;
    private widget.Button BtnBatal;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.TextBox HariPeringatan;
    private widget.CekBox HurufBesar;
    private widget.CekBox HurufKecil;
    private widget.TextBox PanjangMinimal;
    private widget.ScrollPane Scroll;
    private widget.CekBox Simbol;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.panelisi panelGlass5;
    private widget.panelisi panelGlass6;
    private widget.Table tbAturan;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        Valid.tabelKosong(tabMode);
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select set_aturan_password_smc.panjang_minimal, set_aturan_password_smc.huruf_besar, set_aturan_password_smc.huruf_kecil, set_aturan_password_smc.angka, " +
            "set_aturan_password_smc.simbol, set_aturan_password_smc.hari_peringatan from set_aturan_password_smc limit 1"
        ); ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                tabMode.addRow(new Object[] {
                    0 == rs.getInt(1) ? "-" : rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), 0 == rs.getInt(6) ? "-" : rs.getString(6)
                });
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }

    private void getData() {
        int row = tbAturan.getSelectedRow();
        if (row != -1) {
            PanjangMinimal.setText("-".equals(tbAturan.getValueAt(row, 0)) ? "" : tbAturan.getValueAt(row, 0).toString());
            HurufBesar.setSelected("Yes".equals(tbAturan.getValueAt(row, 1)));
            HurufKecil.setSelected("Yes".equals(tbAturan.getValueAt(row, 2)));
            Angka.setSelected("Yes".equals(tbAturan.getValueAt(row, 3)));
            Simbol.setSelected("Yes".equals(tbAturan.getValueAt(row, 4)));
            HariPeringatan.setText("-".equals(tbAturan.getValueAt(row, 5)) ? "" : tbAturan.getValueAt(row, 5).toString());
        }
    }

    public void emptTeks() {
        PanjangMinimal.setText("");
        HurufBesar.setSelected(false);
        HurufKecil.setSelected(false);
        Angka.setSelected(false);
        Simbol.setSelected(false);
        HariPeringatan.setText("");
        tbAturan.clearSelection();
        PanjangMinimal.requestFocus();
    }
}
