/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgObatPenyakit.java
 *
 * Created on May 23, 2010, 12:40:35 AM
 */
package setting;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import inventory.DlgCariJenis;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import simrskhanza.DlgCariBangsal;
import simrskhanza.DlgCariCaraBayar;
import simrskhanza.DlgCariPoli;

/**
 *
 * @author dosen
 */
public final class DlgSetTampilJenisObatResep extends javax.swing.JDialog {
    private final DefaultTableModel tabMode, tabModeRalan, tabModeRanap;
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private final DlgCariCaraBayar carabayar = new DlgCariCaraBayar(null, false);
    private final DlgCariJenis jenis = new DlgCariJenis(null, false);
    private final DlgCariPoli poli = new DlgCariPoli(null, false);
    private final DlgCariBangsal bangsal = new DlgCariBangsal(null, false);

    public DlgSetTampilJenisObatResep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8, 1);
        setSize(885, 674);

        Object[] row = {"Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"},
                 row2 = {"Kode Poliklinik", "Nama Poliklinik", "Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"},
                 row3 = {"Kode Unit Kamar", "Nama Unit Kamar", "Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"};
        
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        tbUmum.setModel(tabMode);
        tbUmum.setPreferredScrollableViewportSize(new Dimension(800, 800));
        tbUmum.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbUmum.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbUmum.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbUmum.getColumnModel().getColumn(2).setPreferredWidth(40);
        tbUmum.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbUmum.setDefaultRenderer(Object.class, new WarnaTable());
        
        tabModeRalan = new DefaultTableModel(null, row2) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        tbRalan.setModel(tabModeRalan);
        tbRalan.setPreferredScrollableViewportSize(new Dimension(800, 800));
        tbRalan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbRalan.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbRalan.getColumnModel().getColumn(1).setPreferredWidth(175);
        tbRalan.getColumnModel().getColumn(2).setPreferredWidth(40);
        tbRalan.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbRalan.getColumnModel().getColumn(4).setPreferredWidth(40);
        tbRalan.getColumnModel().getColumn(5).setPreferredWidth(120);
        tbRalan.setDefaultRenderer(Object.class, new WarnaTable());
        
        tabModeRanap = new DefaultTableModel(null, row3) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        tbRanap.setModel(tabModeRanap);
        tbRanap.setPreferredScrollableViewportSize(new Dimension(800, 800));
        tbRanap.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbRanap.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbRanap.getColumnModel().getColumn(1).setPreferredWidth(175);
        tbRanap.getColumnModel().getColumn(2).setPreferredWidth(40);
        tbRanap.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbRanap.getColumnModel().getColumn(4).setPreferredWidth(40);
        tbRanap.getColumnModel().getColumn(5).setPreferredWidth(120);
        tbRanap.setDefaultRenderer(Object.class, new WarnaTable());

        kdpjRanap.setDocument(new batasInput((byte) 8).getKata(kdpjRanap));
        TCariRalan.setDocument(new batasInput((byte) 100).getKata(TCariRalan));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        tabPane1 = new widget.TabPane();
        jPanel7 = new javax.swing.JPanel();
        panelGlass3 = new widget.panelisi();
        jLabel5 = new widget.Label();
        jLabel6 = new widget.Label();
        pngjawab = new widget.TextBox();
        BtnPilihCaraBayar = new widget.Button();
        kdpj = new widget.TextBox();
        kdjns = new widget.TextBox();
        nmjns = new widget.TextBox();
        BtnPilihJenisObat = new widget.Button();
        Scroll = new widget.ScrollPane();
        tbUmum = new widget.Table();
        jPanel6 = new javax.swing.JPanel();
        panelGlass4 = new widget.panelisi();
        jLabel8 = new widget.Label();
        jLabel12 = new widget.Label();
        pngjawabRalan = new widget.TextBox();
        BtnPilihCaraBayarRalan = new widget.Button();
        kdpjRalan = new widget.TextBox();
        kdjnsRalan = new widget.TextBox();
        nmjnsRalan = new widget.TextBox();
        BtnPilihJenisObatRalan = new widget.Button();
        jLabel13 = new widget.Label();
        kdpoli = new widget.TextBox();
        nmpoli = new widget.TextBox();
        BtnPilihPoli = new widget.Button();
        Scroll1 = new widget.ScrollPane();
        tbRalan = new widget.Table();
        panelGlass13 = new widget.panelisi();
        jLabel9 = new widget.Label();
        TCariRalan = new widget.TextBox();
        BtnCariRalan = new widget.Button();
        BtnAllRalan = new widget.Button();
        jLabel11 = new widget.Label();
        LCount1 = new widget.Label();
        jPanel4 = new javax.swing.JPanel();
        panelGlass2 = new widget.panelisi();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        pngjawabRanap = new widget.TextBox();
        BtnPilihCaraBayarRanap = new widget.Button();
        kdpjRanap = new widget.TextBox();
        kdjnsRanap = new widget.TextBox();
        nmjnsRanap = new widget.TextBox();
        BtnPilihJenisObatRanap = new widget.Button();
        jLabel14 = new widget.Label();
        kdbangsal = new widget.TextBox();
        nmbangsal = new widget.TextBox();
        BtnPilihUnitKamar = new widget.Button();
        Scroll2 = new widget.ScrollPane();
        tbRanap = new widget.Table();
        panelGlass11 = new widget.panelisi();
        jLabel7 = new widget.Label();
        TCariRanap = new widget.TextBox();
        BtnCariRanap = new widget.Button();
        BtnAllRanap = new widget.Button();
        jLabel10 = new widget.Label();
        LCountRanap = new widget.Label();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Setup Tampil Resep Obat, Alkes & BHP Medis per Jenis Obat per Poliklinik / Unit Rawat Inap]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        tabPane1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tabPane1.setName("tabPane1"); // NOI18N

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel7.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass3.setName("panelGlass3"); // NOI18N
        panelGlass3.setPreferredSize(new java.awt.Dimension(711, 77));
        panelGlass3.setLayout(null);

        jLabel5.setText("Cara Bayar :");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass3.add(jLabel5);
        jLabel5.setBounds(0, 12, 80, 23);

        jLabel6.setText("Jenis Obat :");
        jLabel6.setName("jLabel6"); // NOI18N
        panelGlass3.add(jLabel6);
        jLabel6.setBounds(0, 42, 80, 23);

        pngjawab.setEditable(false);
        pngjawab.setHighlighter(null);
        pngjawab.setName("pngjawab"); // NOI18N
        panelGlass3.add(pngjawab);
        pngjawab.setBounds(187, 12, 302, 23);

        BtnPilihCaraBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihCaraBayar.setMnemonic('1');
        BtnPilihCaraBayar.setToolTipText("Alt+1");
        BtnPilihCaraBayar.setName("BtnPilihCaraBayar"); // NOI18N
        BtnPilihCaraBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihCaraBayarActionPerformed(evt);
            }
        });
        panelGlass3.add(BtnPilihCaraBayar);
        BtnPilihCaraBayar.setBounds(493, 12, 28, 23);

        kdpj.setHighlighter(null);
        kdpj.setName("kdpj"); // NOI18N
        panelGlass3.add(kdpj);
        kdpj.setBounds(83, 12, 100, 23);

        kdjns.setHighlighter(null);
        kdjns.setName("kdjns"); // NOI18N
        panelGlass3.add(kdjns);
        kdjns.setBounds(83, 42, 100, 23);

        nmjns.setEditable(false);
        nmjns.setHighlighter(null);
        nmjns.setName("nmjns"); // NOI18N
        panelGlass3.add(nmjns);
        nmjns.setBounds(187, 42, 182, 23);

        BtnPilihJenisObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihJenisObat.setMnemonic('1');
        BtnPilihJenisObat.setToolTipText("Alt+1");
        BtnPilihJenisObat.setName("BtnPilihJenisObat"); // NOI18N
        BtnPilihJenisObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihJenisObatActionPerformed(evt);
            }
        });
        panelGlass3.add(BtnPilihJenisObat);
        BtnPilihJenisObat.setBounds(373, 42, 28, 23);

        jPanel7.add(panelGlass3, java.awt.BorderLayout.PAGE_START);

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbUmum.setAutoCreateRowSorter(true);
        tbUmum.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbUmum.setName("tbUmum"); // NOI18N
        tbUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUmumMouseClicked(evt);
            }
        });
        tbUmum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbUmumKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbUmum);

        jPanel7.add(Scroll, java.awt.BorderLayout.CENTER);

        tabPane1.addTab("Umum", jPanel7);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel6.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass4.setName("panelGlass4"); // NOI18N
        panelGlass4.setPreferredSize(new java.awt.Dimension(711, 107));
        panelGlass4.setLayout(null);

        jLabel8.setText("Cara Bayar :");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass4.add(jLabel8);
        jLabel8.setBounds(0, 42, 80, 23);

        jLabel12.setText("Jenis Obat :");
        jLabel12.setName("jLabel12"); // NOI18N
        panelGlass4.add(jLabel12);
        jLabel12.setBounds(0, 72, 80, 23);

        pngjawabRalan.setEditable(false);
        pngjawabRalan.setHighlighter(null);
        pngjawabRalan.setName("pngjawabRalan"); // NOI18N
        panelGlass4.add(pngjawabRalan);
        pngjawabRalan.setBounds(187, 42, 302, 23);

        BtnPilihCaraBayarRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihCaraBayarRalan.setMnemonic('1');
        BtnPilihCaraBayarRalan.setToolTipText("Alt+1");
        BtnPilihCaraBayarRalan.setName("BtnPilihCaraBayarRalan"); // NOI18N
        BtnPilihCaraBayarRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihCaraBayarRalanActionPerformed(evt);
            }
        });
        panelGlass4.add(BtnPilihCaraBayarRalan);
        BtnPilihCaraBayarRalan.setBounds(493, 42, 28, 23);

        kdpjRalan.setHighlighter(null);
        kdpjRalan.setName("kdpjRalan"); // NOI18N
        panelGlass4.add(kdpjRalan);
        kdpjRalan.setBounds(83, 42, 100, 23);

        kdjnsRalan.setHighlighter(null);
        kdjnsRalan.setName("kdjnsRalan"); // NOI18N
        panelGlass4.add(kdjnsRalan);
        kdjnsRalan.setBounds(83, 72, 100, 23);

        nmjnsRalan.setEditable(false);
        nmjnsRalan.setHighlighter(null);
        nmjnsRalan.setName("nmjnsRalan"); // NOI18N
        panelGlass4.add(nmjnsRalan);
        nmjnsRalan.setBounds(187, 72, 182, 23);

        BtnPilihJenisObatRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihJenisObatRalan.setMnemonic('1');
        BtnPilihJenisObatRalan.setToolTipText("Alt+1");
        BtnPilihJenisObatRalan.setName("BtnPilihJenisObatRalan"); // NOI18N
        BtnPilihJenisObatRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihJenisObatRalanActionPerformed(evt);
            }
        });
        panelGlass4.add(BtnPilihJenisObatRalan);
        BtnPilihJenisObatRalan.setBounds(373, 72, 28, 23);

        jLabel13.setText("Poliklinik :");
        jLabel13.setName("jLabel13"); // NOI18N
        panelGlass4.add(jLabel13);
        jLabel13.setBounds(0, 12, 80, 23);

        kdpoli.setHighlighter(null);
        kdpoli.setName("kdpoli"); // NOI18N
        panelGlass4.add(kdpoli);
        kdpoli.setBounds(83, 12, 100, 23);

        nmpoli.setEditable(false);
        nmpoli.setHighlighter(null);
        nmpoli.setName("nmpoli"); // NOI18N
        panelGlass4.add(nmpoli);
        nmpoli.setBounds(187, 12, 302, 23);

        BtnPilihPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihPoli.setMnemonic('1');
        BtnPilihPoli.setToolTipText("Alt+1");
        BtnPilihPoli.setName("BtnPilihPoli"); // NOI18N
        BtnPilihPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihPoliActionPerformed(evt);
            }
        });
        panelGlass4.add(BtnPilihPoli);
        BtnPilihPoli.setBounds(493, 12, 28, 23);

        jPanel6.add(panelGlass4, java.awt.BorderLayout.PAGE_START);

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        tbRalan.setAutoCreateRowSorter(true);
        tbRalan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRalan.setName("tbRalan"); // NOI18N
        tbRalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRalanMouseClicked(evt);
            }
        });
        tbRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRalanKeyPressed(evt);
            }
        });
        Scroll1.setViewportView(tbRalan);

        jPanel6.add(Scroll1, java.awt.BorderLayout.CENTER);

        panelGlass13.setName("panelGlass13"); // NOI18N
        panelGlass13.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel9.setText("Key Word :");
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass13.add(jLabel9);

        TCariRalan.setName("TCariRalan"); // NOI18N
        TCariRalan.setPreferredSize(new java.awt.Dimension(360, 23));
        TCariRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(TCariRalan);

        BtnCariRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCariRalan.setMnemonic('5');
        BtnCariRalan.setToolTipText("Alt+5");
        BtnCariRalan.setName("BtnCariRalan"); // NOI18N
        BtnCariRalan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCariRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariRalanActionPerformed(evt);
            }
        });
        BtnCariRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(BtnCariRalan);

        BtnAllRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAllRalan.setMnemonic('M');
        BtnAllRalan.setToolTipText("Alt+M");
        BtnAllRalan.setName("BtnAllRalan"); // NOI18N
        BtnAllRalan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAllRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllRalanActionPerformed(evt);
            }
        });
        BtnAllRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(BtnAllRalan);

        jLabel11.setText("Record :");
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelGlass13.add(jLabel11);

        LCount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount1.setText("0");
        LCount1.setName("LCount1"); // NOI18N
        LCount1.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass13.add(LCount1);

        jPanel6.add(panelGlass13, java.awt.BorderLayout.PAGE_END);

        tabPane1.addTab("Rawat Jalan", jPanel6);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel4.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass2.setName("panelGlass2"); // NOI18N
        panelGlass2.setPreferredSize(new java.awt.Dimension(711, 107));
        panelGlass2.setLayout(null);

        jLabel3.setText("Cara Bayar :");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass2.add(jLabel3);
        jLabel3.setBounds(0, 42, 80, 23);

        jLabel4.setText("Jenis Obat :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass2.add(jLabel4);
        jLabel4.setBounds(0, 72, 80, 23);

        pngjawabRanap.setEditable(false);
        pngjawabRanap.setHighlighter(null);
        pngjawabRanap.setName("pngjawabRanap"); // NOI18N
        panelGlass2.add(pngjawabRanap);
        pngjawabRanap.setBounds(187, 42, 302, 23);

        BtnPilihCaraBayarRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihCaraBayarRanap.setMnemonic('1');
        BtnPilihCaraBayarRanap.setToolTipText("Alt+1");
        BtnPilihCaraBayarRanap.setName("BtnPilihCaraBayarRanap"); // NOI18N
        BtnPilihCaraBayarRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihCaraBayarRanapActionPerformed(evt);
            }
        });
        panelGlass2.add(BtnPilihCaraBayarRanap);
        BtnPilihCaraBayarRanap.setBounds(493, 42, 28, 23);

        kdpjRanap.setHighlighter(null);
        kdpjRanap.setName("kdpjRanap"); // NOI18N
        panelGlass2.add(kdpjRanap);
        kdpjRanap.setBounds(83, 42, 100, 23);

        kdjnsRanap.setHighlighter(null);
        kdjnsRanap.setName("kdjnsRanap"); // NOI18N
        panelGlass2.add(kdjnsRanap);
        kdjnsRanap.setBounds(83, 72, 100, 23);

        nmjnsRanap.setEditable(false);
        nmjnsRanap.setHighlighter(null);
        nmjnsRanap.setName("nmjnsRanap"); // NOI18N
        panelGlass2.add(nmjnsRanap);
        nmjnsRanap.setBounds(187, 72, 182, 23);

        BtnPilihJenisObatRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihJenisObatRanap.setMnemonic('1');
        BtnPilihJenisObatRanap.setToolTipText("Alt+1");
        BtnPilihJenisObatRanap.setName("BtnPilihJenisObatRanap"); // NOI18N
        BtnPilihJenisObatRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihJenisObatRanapActionPerformed(evt);
            }
        });
        panelGlass2.add(BtnPilihJenisObatRanap);
        BtnPilihJenisObatRanap.setBounds(373, 72, 28, 23);

        jLabel14.setText("Unit Kamar :");
        jLabel14.setName("jLabel14"); // NOI18N
        panelGlass2.add(jLabel14);
        jLabel14.setBounds(0, 12, 80, 23);

        kdbangsal.setHighlighter(null);
        kdbangsal.setName("kdbangsal"); // NOI18N
        panelGlass2.add(kdbangsal);
        kdbangsal.setBounds(83, 12, 100, 23);

        nmbangsal.setEditable(false);
        nmbangsal.setHighlighter(null);
        nmbangsal.setName("nmbangsal"); // NOI18N
        panelGlass2.add(nmbangsal);
        nmbangsal.setBounds(187, 12, 302, 23);

        BtnPilihUnitKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihUnitKamar.setMnemonic('1');
        BtnPilihUnitKamar.setToolTipText("Alt+1");
        BtnPilihUnitKamar.setName("BtnPilihUnitKamar"); // NOI18N
        BtnPilihUnitKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihUnitKamarActionPerformed(evt);
            }
        });
        panelGlass2.add(BtnPilihUnitKamar);
        BtnPilihUnitKamar.setBounds(493, 12, 28, 23);

        jPanel4.add(panelGlass2, java.awt.BorderLayout.PAGE_START);

        Scroll2.setName("Scroll2"); // NOI18N
        Scroll2.setOpaque(true);

        tbRanap.setAutoCreateRowSorter(true);
        tbRanap.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRanap.setName("tbRanap"); // NOI18N
        tbRanap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRanapMouseClicked(evt);
            }
        });
        tbRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRanapKeyPressed(evt);
            }
        });
        Scroll2.setViewportView(tbRanap);

        jPanel4.add(Scroll2, java.awt.BorderLayout.CENTER);

        panelGlass11.setName("panelGlass11"); // NOI18N
        panelGlass11.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel7.setText("Key Word :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass11.add(jLabel7);

        TCariRanap.setName("TCariRanap"); // NOI18N
        TCariRanap.setPreferredSize(new java.awt.Dimension(360, 23));
        TCariRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(TCariRanap);

        BtnCariRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCariRanap.setMnemonic('5');
        BtnCariRanap.setToolTipText("Alt+5");
        BtnCariRanap.setName("BtnCariRanap"); // NOI18N
        BtnCariRanap.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCariRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariRanapActionPerformed(evt);
            }
        });
        BtnCariRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(BtnCariRanap);

        BtnAllRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAllRanap.setMnemonic('M');
        BtnAllRanap.setToolTipText("Alt+M");
        BtnAllRanap.setName("BtnAllRanap"); // NOI18N
        BtnAllRanap.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAllRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllRanapActionPerformed(evt);
            }
        });
        BtnAllRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(BtnAllRanap);

        jLabel10.setText("Record :");
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(55, 23));
        panelGlass11.add(jLabel10);

        LCountRanap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCountRanap.setText("0");
        LCountRanap.setName("LCountRanap"); // NOI18N
        LCountRanap.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass11.add(LCountRanap);

        jPanel4.add(panelGlass11, java.awt.BorderLayout.PAGE_END);

        tabPane1.addTab("Rawat Inap", jPanel4);

        internalFrame1.add(tabPane1, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis...!!!!");
            kdpjRanap.requestFocus();
        } else if (pngjawabRanap.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Gagal menghapus. Pilih dulu data yang mau dihapus.\nKlik data pada table untuk memilih...!!!!");
        } else if (!(pngjawabRanap.getText().trim().equals(""))) {
            Valid.hapusTable(tabMode, kdpjRanap, "set_harga_obat_ralan", "kd_pj");
            tampil();
            emptTeks();
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnPilihCaraBayarRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihCaraBayarRanapActionPerformed
        penjab.isCek();
        penjab.emptTeks();
        penjab.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
        penjab.setLocationRelativeTo(internalFrame1);
        penjab.setVisible(true);
    }//GEN-LAST:event_BtnPilihCaraBayarRanapActionPerformed

    private void tbUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUmumMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
    }//GEN-LAST:event_tbUmumMouseClicked

    private void tbUmumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUmumKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
    }//GEN-LAST:event_tbUmumKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        penjab.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (penjab.getTable().getSelectedRow() != -1) {
                    kdpjRanap.setText(penjab.getTable().getValueAt(penjab.getTable().getSelectedRow(), 1).toString());
                    pngjawabRanap.setText(penjab.getTable().getValueAt(penjab.getTable().getSelectedRow(), 2).toString());
                }
                kdpjRanap.requestFocus();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });

        penjab.getTable().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                    penjab.dispose();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        penjab.removeWindowListener(null);
        penjab.getTable().removeKeyListener(null);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
        emptTeks();
    }//GEN-LAST:event_formWindowOpened

    private void tbRanapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRanapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRanapMouseClicked

    private void tbRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRanapKeyPressed

    private void tbRalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRalanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalanMouseClicked

    private void tbRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalanKeyPressed

    private void BtnPilihJenisObatRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihJenisObatRanapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihJenisObatRanapActionPerformed

    private void TCariRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariRanapKeyPressed

    private void BtnCariRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariRanapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRanapActionPerformed

    private void BtnCariRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRanapKeyPressed

    private void BtnAllRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllRanapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRanapActionPerformed

    private void BtnAllRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRanapKeyPressed

    private void TCariRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariRalanKeyPressed

    private void BtnCariRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRalanActionPerformed

    private void BtnCariRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRalanKeyPressed

    private void BtnAllRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRalanActionPerformed

    private void BtnAllRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRalanKeyPressed

    private void BtnPilihCaraBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihCaraBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihCaraBayarActionPerformed

    private void BtnPilihJenisObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihJenisObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihJenisObatActionPerformed

    private void BtnPilihCaraBayarRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihCaraBayarRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihCaraBayarRalanActionPerformed

    private void BtnPilihJenisObatRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihJenisObatRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihJenisObatRalanActionPerformed

    private void BtnPilihPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihPoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihPoliActionPerformed

    private void BtnPilihUnitKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihUnitKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihUnitKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSetTampilJenisObatResep dialog = new DlgSetTampilJenisObatResep(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAllRalan;
    private widget.Button BtnAllRanap;
    private widget.Button BtnBatal;
    private widget.Button BtnCariRalan;
    private widget.Button BtnCariRanap;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPilihCaraBayar;
    private widget.Button BtnPilihCaraBayarRalan;
    private widget.Button BtnPilihCaraBayarRanap;
    private widget.Button BtnPilihJenisObat;
    private widget.Button BtnPilihJenisObatRalan;
    private widget.Button BtnPilihJenisObatRanap;
    private widget.Button BtnPilihPoli;
    private widget.Button BtnPilihUnitKamar;
    private widget.Button BtnSimpan;
    private widget.Label LCount1;
    private widget.Label LCountRanap;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.ScrollPane Scroll2;
    private widget.TextBox TCariRalan;
    private widget.TextBox TCariRanap;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.Label jLabel13;
    private widget.Label jLabel14;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private widget.Label jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private widget.TextBox kdbangsal;
    private widget.TextBox kdjns;
    private widget.TextBox kdjnsRalan;
    private widget.TextBox kdjnsRanap;
    private widget.TextBox kdpj;
    private widget.TextBox kdpjRalan;
    private widget.TextBox kdpjRanap;
    private widget.TextBox kdpoli;
    private widget.TextBox nmbangsal;
    private widget.TextBox nmjns;
    private widget.TextBox nmjnsRalan;
    private widget.TextBox nmjnsRanap;
    private widget.TextBox nmpoli;
    private widget.panelisi panelGlass11;
    private widget.panelisi panelGlass13;
    private widget.panelisi panelGlass2;
    private widget.panelisi panelGlass3;
    private widget.panelisi panelGlass4;
    private widget.panelisi panelGlass8;
    private widget.TextBox pngjawab;
    private widget.TextBox pngjawabRalan;
    private widget.TextBox pngjawabRanap;
    private widget.TabPane tabPane1;
    private widget.Table tbRalan;
    private widget.Table tbRanap;
    private widget.Table tbUmum;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        String sql = "select set_harga_obat_ralan.kd_pj,penjab.png_jawab, set_harga_obat_ralan.hargajual "
            + "from set_harga_obat_ralan inner join penjab on set_harga_obat_ralan.kd_pj=penjab.kd_pj "
            + "where set_harga_obat_ralan.kd_pj like '%" + TCari.getText().trim() + "%' or "
            + "penjab.png_jawab like '%" + TCari.getText().trim() + "%' or "
            + "set_harga_obat_ralan.hargajual like '%" + TCari.getText().trim() + "%' order by penjab.png_jawab";
        prosesCari(sql);
    }

    private void prosesCari(String sql) {
        Valid.tabelKosong(tabMode);
        try {
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String[] data = {rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)};
                tabMode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println("Notifikasi : " + e);
        }
        int b = tabMode.getRowCount();
        LCountRanap.setText("" + b);
    }

    private void emptTeks() {
        harga.setText("0");
        kdpjRanap.setText("");
        pngjawabRanap.setText("");
        harga.requestFocus();
    }

    private void getData() {
        int row = tbUmum.getSelectedRow();
        if (row != -1) {
            kdpjRanap.setText(tbUmum.getValueAt(row, 0).toString());
            pngjawabRanap.setText(tbUmum.getValueAt(row, 1).toString());
            harga.setText(tbUmum.getValueAt(row, 2).toString());
        }
    }
}
