/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgObatPenyakit.java
 *
 * Created on May 23, 2010, 12:40:35 AM
 */
package setting;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import inventory.DlgCariJenis;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import simrskhanza.DlgCariBangsal;
import simrskhanza.DlgCariCaraBayar;
import simrskhanza.DlgCariPoli;

/**
 *
 * @author dosen
 */
public final class DlgSetTampilJenisObatResep extends javax.swing.JDialog {
    private final DefaultTableModel tabMode, tabModeRalan, tabModeRanap;
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final Connection koneksi = koneksiDB.condb();
    private final DlgCariCaraBayar carabayar = new DlgCariCaraBayar(null, false);
    private final DlgCariJenis jenis = new DlgCariJenis(null, false);
    private final DlgCariPoli poli = new DlgCariPoli(null, false);
    private final DlgCariBangsal bangsal = new DlgCariBangsal(null, false);

    public DlgSetTampilJenisObatResep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8, 1);
        setSize(885, 674);

        Object[] row = {"Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"},
                 row2 = {"Kode Poliklinik", "Nama Poliklinik", "Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"},
                 row3 = {"Kode Unit Kamar", "Nama Unit Kamar", "Kode Jenis", "Nama Jenis Bayar", "Kode Jenis Obat", "Nama Jenis Obat"};
        
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        tabModeRalan 
        
        tbRalan.setModel(tabMode);
        tbRalan.setPreferredScrollableViewportSize(new Dimension(800, 800));
        tbRalan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbRalan.getColumnModel().getColumn(0).setPreferredWidth(40);
        tbRalan.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbRalan.getColumnModel().getColumn(2).setPreferredWidth(40);
        tbRalan.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbRalan.setDefaultRenderer(Object.class, new WarnaTable());

        harga.setDocument(new batasInput((byte) 4).getOnlyAngka(harga));
        kdpj.setDocument(new batasInput((byte) 8).getKata(kdpj));
        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampil();
                    }
                }
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass2 = new widget.panelisi();
        jLabel3 = new widget.Label();
        jLabel4 = new widget.Label();
        nmpj = new widget.TextBox();
        BtnSeek = new widget.Button();
        kdpj = new widget.TextBox();
        kdjns = new widget.TextBox();
        nmjns = new widget.TextBox();
        BtnPilihJenisObat = new widget.Button();
        tabPane1 = new widget.TabPane();
        Scroll = new widget.ScrollPane();
        tbRalan = new widget.Table();
        jPanel6 = new javax.swing.JPanel();
        Scroll1 = new widget.ScrollPane();
        tbRalan2 = new widget.Table();
        panelGlass13 = new widget.panelisi();
        jLabel9 = new widget.Label();
        TCariRalan = new widget.TextBox();
        BtnCariRalan = new widget.Button();
        BtnAllRalan = new widget.Button();
        jLabel11 = new widget.Label();
        LCount1 = new widget.Label();
        jPanel4 = new javax.swing.JPanel();
        Scroll2 = new widget.ScrollPane();
        tbRalan1 = new widget.Table();
        panelGlass11 = new widget.panelisi();
        jLabel7 = new widget.Label();
        TCariRanap = new widget.TextBox();
        BtnCariRanap = new widget.Button();
        BtnAllRanap = new widget.Button();
        jLabel10 = new widget.Label();
        LCount2 = new widget.Label();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Setup Tampil Resep Obat, Alkes & BHP Medis per Jenis ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass2.setName("panelGlass2"); // NOI18N
        panelGlass2.setPreferredSize(new java.awt.Dimension(711, 77));
        panelGlass2.setLayout(null);

        jLabel3.setText("Cara Bayar :");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass2.add(jLabel3);
        jLabel3.setBounds(0, 12, 80, 23);

        jLabel4.setText("Jenis Obat :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass2.add(jLabel4);
        jLabel4.setBounds(0, 42, 80, 23);

        nmpj.setEditable(false);
        nmpj.setHighlighter(null);
        nmpj.setName("nmpj"); // NOI18N
        panelGlass2.add(nmpj);
        nmpj.setBounds(187, 12, 302, 23);

        BtnSeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnSeek.setMnemonic('1');
        BtnSeek.setToolTipText("Alt+1");
        BtnSeek.setName("BtnSeek"); // NOI18N
        BtnSeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeekActionPerformed(evt);
            }
        });
        panelGlass2.add(BtnSeek);
        BtnSeek.setBounds(493, 12, 28, 23);

        kdpj.setHighlighter(null);
        kdpj.setName("kdpj"); // NOI18N
        panelGlass2.add(kdpj);
        kdpj.setBounds(83, 12, 100, 23);

        kdjns.setHighlighter(null);
        kdjns.setName("kdjns"); // NOI18N
        panelGlass2.add(kdjns);
        kdjns.setBounds(83, 42, 100, 23);

        nmjns.setEditable(false);
        nmjns.setHighlighter(null);
        nmjns.setName("nmjns"); // NOI18N
        panelGlass2.add(nmjns);
        nmjns.setBounds(187, 42, 182, 23);

        BtnPilihJenisObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPilihJenisObat.setMnemonic('1');
        BtnPilihJenisObat.setToolTipText("Alt+1");
        BtnPilihJenisObat.setName("BtnPilihJenisObat"); // NOI18N
        BtnPilihJenisObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihJenisObatActionPerformed(evt);
            }
        });
        panelGlass2.add(BtnPilihJenisObat);
        BtnPilihJenisObat.setBounds(373, 42, 28, 23);

        internalFrame1.add(panelGlass2, java.awt.BorderLayout.PAGE_START);

        tabPane1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tabPane1.setName("tabPane1"); // NOI18N

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbRalan.setAutoCreateRowSorter(true);
        tbRalan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRalan.setName("tbRalan"); // NOI18N
        tbRalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRalanMouseClicked(evt);
            }
        });
        tbRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRalanKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbRalan);

        tabPane1.addTab("Umum", Scroll);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel6.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        tbRalan2.setAutoCreateRowSorter(true);
        tbRalan2.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRalan2.setName("tbRalan2"); // NOI18N
        tbRalan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRalan2MouseClicked(evt);
            }
        });
        tbRalan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRalan2KeyPressed(evt);
            }
        });
        Scroll1.setViewportView(tbRalan2);

        jPanel6.add(Scroll1, java.awt.BorderLayout.CENTER);

        panelGlass13.setName("panelGlass13"); // NOI18N
        panelGlass13.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel9.setText("Key Word :");
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass13.add(jLabel9);

        TCariRalan.setName("TCariRalan"); // NOI18N
        TCariRalan.setPreferredSize(new java.awt.Dimension(360, 23));
        TCariRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(TCariRalan);

        BtnCariRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCariRalan.setMnemonic('5');
        BtnCariRalan.setToolTipText("Alt+5");
        BtnCariRalan.setName("BtnCariRalan"); // NOI18N
        BtnCariRalan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCariRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariRalanActionPerformed(evt);
            }
        });
        BtnCariRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(BtnCariRalan);

        BtnAllRalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAllRalan.setMnemonic('M');
        BtnAllRalan.setToolTipText("Alt+M");
        BtnAllRalan.setName("BtnAllRalan"); // NOI18N
        BtnAllRalan.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAllRalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllRalanActionPerformed(evt);
            }
        });
        BtnAllRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllRalanKeyPressed(evt);
            }
        });
        panelGlass13.add(BtnAllRalan);

        jLabel11.setText("Record :");
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelGlass13.add(jLabel11);

        LCount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount1.setText("0");
        LCount1.setName("LCount1"); // NOI18N
        LCount1.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass13.add(LCount1);

        jPanel6.add(panelGlass13, java.awt.BorderLayout.PAGE_END);

        tabPane1.addTab("Rawat Jalan", jPanel6);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel4.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll2.setName("Scroll2"); // NOI18N
        Scroll2.setOpaque(true);

        tbRalan1.setAutoCreateRowSorter(true);
        tbRalan1.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRalan1.setName("tbRalan1"); // NOI18N
        tbRalan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRalan1MouseClicked(evt);
            }
        });
        tbRalan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRalan1KeyPressed(evt);
            }
        });
        Scroll2.setViewportView(tbRalan1);

        jPanel4.add(Scroll2, java.awt.BorderLayout.CENTER);

        panelGlass11.setName("panelGlass11"); // NOI18N
        panelGlass11.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        jLabel7.setText("Key Word :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass11.add(jLabel7);

        TCariRanap.setName("TCariRanap"); // NOI18N
        TCariRanap.setPreferredSize(new java.awt.Dimension(360, 23));
        TCariRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(TCariRanap);

        BtnCariRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCariRanap.setMnemonic('5');
        BtnCariRanap.setToolTipText("Alt+5");
        BtnCariRanap.setName("BtnCariRanap"); // NOI18N
        BtnCariRanap.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCariRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariRanapActionPerformed(evt);
            }
        });
        BtnCariRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(BtnCariRanap);

        BtnAllRanap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAllRanap.setMnemonic('M');
        BtnAllRanap.setToolTipText("Alt+M");
        BtnAllRanap.setName("BtnAllRanap"); // NOI18N
        BtnAllRanap.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAllRanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllRanapActionPerformed(evt);
            }
        });
        BtnAllRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllRanapKeyPressed(evt);
            }
        });
        panelGlass11.add(BtnAllRanap);

        jLabel10.setText("Record :");
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(55, 23));
        panelGlass11.add(jLabel10);

        LCount2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount2.setText("0");
        LCount2.setName("LCount2"); // NOI18N
        LCount2.setPreferredSize(new java.awt.Dimension(40, 23));
        panelGlass11.add(LCount2);

        jPanel4.add(panelGlass11, java.awt.BorderLayout.PAGE_END);

        tabPane1.addTab("Rawat Inap", jPanel4);

        internalFrame1.add(tabPane1, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        BtnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnBatalKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (nmpj.getText().trim().equals("")) {
            Valid.textKosong(nmpj, "Jenis Bayar");
        } else {
            Sequel.menyimpan("set_harga_obat_ralan", "'" + kdpj.getText() + "','" + harga.getText() + "'", "Jenis Bayar");
            tampil();
            emptTeks();
        }
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnSimpanActionPerformed(null);
        } else {
            Valid.pindah(evt, harga, BtnBatal);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        emptTeks();
}//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnBatalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            emptTeks();
        } else {
            Valid.pindah(evt, BtnSimpan, BtnHapus);
        }
}//GEN-LAST:event_BtnBatalKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis...!!!!");
            kdpj.requestFocus();
        } else if (nmpj.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Gagal menghapus. Pilih dulu data yang mau dihapus.\nKlik data pada table untuk memilih...!!!!");
        } else if (!(nmpj.getText().trim().equals(""))) {
            Valid.hapusTable(tabMode, kdpj, "set_harga_obat_ralan", "kd_pj");
            tampil();
            emptTeks();
        }
}//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnHapusActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnBatal, BtnKeluar);
        }
}//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnAll, BtnSimpan);
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnSeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeekActionPerformed
        penjab.isCek();
        penjab.emptTeks();
        penjab.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
        penjab.setLocationRelativeTo(internalFrame1);
        penjab.setVisible(true);
}//GEN-LAST:event_BtnSeekActionPerformed

    private void tbRalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRalanMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                getData();
            } catch (java.lang.NullPointerException e) {
            }
        }
}//GEN-LAST:event_tbRalanMouseClicked

    private void tbRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRalanKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
}//GEN-LAST:event_tbRalanKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        penjab.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                if (penjab.getTable().getSelectedRow() != -1) {
                    kdpj.setText(penjab.getTable().getValueAt(penjab.getTable().getSelectedRow(), 1).toString());
                    nmpj.setText(penjab.getTable().getValueAt(penjab.getTable().getSelectedRow(), 2).toString());
                }
                kdpj.requestFocus();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });

        penjab.getTable().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                    penjab.dispose();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        penjab.removeWindowListener(null);
        penjab.getTable().removeKeyListener(null);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
        emptTeks();
    }//GEN-LAST:event_formWindowOpened

    private void tbRalan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRalan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalan1MouseClicked

    private void tbRalan1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRalan1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalan1KeyPressed

    private void tbRalan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRalan2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalan2MouseClicked

    private void tbRalan2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRalan2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRalan2KeyPressed

    private void BtnPilihJenisObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihJenisObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPilihJenisObatActionPerformed

    private void TCariRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariRanapKeyPressed

    private void BtnCariRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariRanapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRanapActionPerformed

    private void BtnCariRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRanapKeyPressed

    private void BtnAllRanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllRanapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRanapActionPerformed

    private void BtnAllRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRanapKeyPressed

    private void TCariRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariRalanKeyPressed

    private void BtnCariRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRalanActionPerformed

    private void BtnCariRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCariRalanKeyPressed

    private void BtnAllRalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllRalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRalanActionPerformed

    private void BtnAllRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllRalanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAllRalanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSetTampilJenisObatResep dialog = new DlgSetTampilJenisObatResep(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAllRalan;
    private widget.Button BtnAllRanap;
    private widget.Button BtnBatal;
    private widget.Button BtnCariRalan;
    private widget.Button BtnCariRanap;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPilihJenisObat;
    private widget.Button BtnSeek;
    private widget.Button BtnSimpan;
    private widget.Label LCount1;
    private widget.Label LCount2;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.ScrollPane Scroll2;
    private widget.TextBox TCariRalan;
    private widget.TextBox TCariRanap;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel7;
    private widget.Label jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private widget.TextBox kdjns;
    private widget.TextBox kdpj;
    private widget.TextBox nmjns;
    private widget.TextBox nmpj;
    private widget.panelisi panelGlass11;
    private widget.panelisi panelGlass13;
    private widget.panelisi panelGlass2;
    private widget.panelisi panelGlass8;
    private widget.TabPane tabPane1;
    private widget.Table tbRalan;
    private widget.Table tbRalan1;
    private widget.Table tbRalan2;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        String sql = "select set_harga_obat_ralan.kd_pj,penjab.png_jawab, set_harga_obat_ralan.hargajual "
            + "from set_harga_obat_ralan inner join penjab on set_harga_obat_ralan.kd_pj=penjab.kd_pj "
            + "where set_harga_obat_ralan.kd_pj like '%" + TCari.getText().trim() + "%' or "
            + "penjab.png_jawab like '%" + TCari.getText().trim() + "%' or "
            + "set_harga_obat_ralan.hargajual like '%" + TCari.getText().trim() + "%' order by penjab.png_jawab";
        prosesCari(sql);
    }

    private void prosesCari(String sql) {
        Valid.tabelKosong(tabMode);
        try {
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String[] data = {rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)};
                tabMode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println("Notifikasi : " + e);
        }
        int b = tabMode.getRowCount();
        LCount2.setText("" + b);
    }

    private void emptTeks() {
        harga.setText("0");
        kdpj.setText("");
        nmpj.setText("");
        harga.requestFocus();
    }

    private void getData() {
        int row = tbRalan.getSelectedRow();
        if (row != -1) {
            kdpj.setText(tbRalan.getValueAt(row, 0).toString());
            nmpj.setText(tbRalan.getValueAt(row, 1).toString());
            harga.setText(tbRalan.getValueAt(row, 2).toString());
        }
    }

}
