/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package bridging.satusehat.klaim;

import bridging.satusehat.ApiSNOMED;
import com.fasterxml.jackson.databind.JsonNode;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 * Pencarian kode SNOMED PROFESI (PractitionerRole.code[]) — dipakai Master Dokter (DlgDokter).
 *
 * Dua sumber: kode yang sudah tersimpan di `satu_sehat_referensi_profesi_snomed` jenis 'role'
 * (530 kode dari Lampiran Terminologi Occupation, cepat & offline) dan pencarian langsung ke
 * server SNOMED lewat {@link ApiSNOMED} untuk kode di luar lampiran. Hasil server yang
 * benar-benar dipakai ikut tersimpan ke referensi lokal.
 *
 * Tanpa kolom nama Indonesia: lampiran occupation memang tidak menerjemahkan.
 * Pasangannya {@link SatuSehatReferensiSNOMEDSpesialisasi} yang punya terjemahan.
 */
public final class SatuSehatReferensiSNOMEDProfesi extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final Connection koneksi=koneksiDB.condb();
    private final sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private int i=0;
    private final String jenis="role";
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;

    /** Creates new form SatuSehatReferensiSNOMEDProfesi
     * @param parent
     * @param modal */
    public SatuSehatReferensiSNOMEDProfesi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(10,2);
        setSize(700,674);

        tabMode=new DefaultTableModel(null,new String[]{"Code","Display","System","Sumber"}){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbKamar.setModel(tabMode);

        tbKamar.setPreferredScrollableViewportSize(new Dimension(600,500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 4; i++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(110);
            }else if(i==1){
                column.setPreferredWidth(320);
            }else if(i==2){
                column.setPreferredWidth(180);
            }else if(i==3){
                column.setPreferredWidth(80);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());

        Keyword.setDocument(new batasInput((byte)100).getKata(Keyword));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelGlass6 = new widget.panelisi();
        jLabel16 = new widget.Label();
        Keyword = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnServer = new widget.Button();
        jLabel17 = new widget.Label();
        BtnPilih = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pencarian Kode SNOMED Profesi Satu Sehat ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setToolTipText("Klik ganda atau tekan spasi untuk memilih kode");
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel16.setText("Key Word :");
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass6.add(jLabel16);

        Keyword.setToolTipText("Kosongkan lalu cari untuk menampilkan semua kode tersimpan");
        Keyword.setName("Keyword"); // NOI18N
        Keyword.setPreferredSize(new java.awt.Dimension(240, 23));
        Keyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeywordKeyPressed(evt);
            }
        });
        panelGlass6.add(Keyword);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6, cari di kode yang sudah tersimpan");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnCari);

        BtnServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnServer.setMnemonic('7');
        BtnServer.setText("Cari SNOMED");
        BtnServer.setToolTipText("Alt+7, cari kode langsung ke server SNOMED");
        BtnServer.setName("BtnServer"); // NOI18N
        BtnServer.setPreferredSize(new java.awt.Dimension(130, 23));
        BtnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnServerActionPerformed(evt);
            }
        });
        BtnServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnServerKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnServer);

        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(20, 23));
        panelGlass6.add(jLabel17);

        BtnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnPilih.setMnemonic('P');
        BtnPilih.setText("Pilih");
        BtnPilih.setToolTipText("Alt+P");
        BtnPilih.setName("BtnPilih"); // NOI18N
        BtnPilih.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPilihActionPerformed(evt);
            }
        });
        BtnPilih.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPilihKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnPilih);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        tbKamar.clearSelection();
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnKeluarActionPerformed(null);
        }else{Valid.pindah(evt,BtnPilih,BtnKeluar);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void KeywordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeywordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            tbKamar.requestFocus();
        }
    }//GEN-LAST:event_KeywordKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil(Keyword.getText());
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt,Keyword,BtnServer);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnServerActionPerformed
        final String kata=Keyword.getText().trim();
        if(kata.equals("")){
            Valid.textKosong(Keyword,"kata kunci pencarian");
            return;
        }
        runBackground(() ->cariServer(kata));
    }//GEN-LAST:event_BtnServerActionPerformed

    private void BtnServerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnServerKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnServerActionPerformed(null);
        }else{
            Valid.pindah(evt,BtnCari,BtnPilih);
        }
    }//GEN-LAST:event_BtnServerKeyPressed

    private void BtnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPilihActionPerformed
        pilih();
    }//GEN-LAST:event_BtnPilihActionPerformed

    private void BtnPilihKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPilihKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            pilih();
        }else{
            Valid.pindah(evt,BtnServer,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPilihKeyPressed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(evt.getClickCount()==2){
            pilih();
        }
    }//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed
        if(tabMode.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_SPACE)||(evt.getKeyCode()==KeyEvent.VK_ENTER)){
                pilih();
            }else if(evt.getKeyCode()==KeyEvent.VK_SHIFT){
                Keyword.setText("");
                Keyword.requestFocus();
            }
        }
    }//GEN-LAST:event_tbKamarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil("");
        if(koneksiDB.CARICEPAT().equals("aktif")){
            Keyword.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(Keyword.getText().length()>2){
                        tampil(Keyword.getText());
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(Keyword.getText().length()>2){
                        tampil(Keyword.getText());
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(Keyword.getText().length()>2){
                        tampil(Keyword.getText());
                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            SatuSehatReferensiSNOMEDProfesi dialog = new SatuSehatReferensiSNOMEDProfesi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPilih;
    private widget.Button BtnServer;
    private widget.TextBox Keyword;
    private widget.ScrollPane Scroll;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.panelisi panelGlass6;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    /** Kode yang sudah tersimpan di referensi lokal. */
    private void tampil(String cari) {
        try {
            Valid.tabelKosong(tabMode);
            //Tanpa nama_id: lampiran occupation tidak menerjemahkan, jadi kolomnya selalu kosong.
            PreparedStatement p=koneksi.prepareStatement(
                    "select kode,nama from satu_sehat_referensi_profesi_snomed "+
                    "where jenis=? and (kode like ? or nama like ?) order by nama");
            p.setString(1,jenis);
            p.setString(2,"%"+cari.trim()+"%");
            p.setString(3,"%"+cari.trim()+"%");
            ResultSet r=p.executeQuery();
            while(r.next()){
                tabMode.addRow(new Object[]{
                    r.getString("kode"),r.getString("nama"),"http://snomed.info/sct","Tersimpan"
                });
            }
            r.close();
            p.close();
        } catch (Exception ex) {
            System.out.println("Notifikasi : "+ex);
        }
    }

    /** Pencarian langsung ke server SNOMED; hasilnya ditandai "SNOMED" sampai benar-benar dipakai. */
    private void cariServer(String kata) {
        ApiSNOMED snomed=new ApiSNOMED(this);
        ApiSNOMED.SnomedSearchResult hasil=snomed.searchSnomedConcepts(kata,50,0);
        if(!hasil.isSuccess()){
            SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(null,"Maaf, pencarian SNOMED gagal.\n"+hasil.getErrorMessage()));
            return;
        }
        if(hasil.getConcepts()==null||hasil.getConcepts().size()==0){
            SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(null,"Maaf, tidak ada kode SNOMED untuk '"+kata+"'...!!!"));
            return;
        }
        final List<Object[]> baris=new ArrayList<>();
        for(JsonNode konsep:hasil.getConcepts()){
            baris.add(new Object[]{
                konsep.path("code").asText(),
                konsep.path("display").asText(),
                konsep.path("system").asText(),
                "SNOMED"
            });
        }
        SwingUtilities.invokeLater(() -> {
            Valid.tabelKosong(tabMode);
            for(Object[] b:baris){
                tabMode.addRow(b);
            }
        });
    }

    /**
     * Tutup form dengan baris terpilih. Kode hasil pencarian server ikut disimpan ke referensi
     * lokal supaya lain kali tidak perlu memanggil server lagi.
     */
    private void pilih(){
        int row=tbKamar.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(null,"Maaf, silahkan pilih dulu kodenya...!!!");
            return;
        }
        if("SNOMED".equals(tbKamar.getValueAt(row,3)+"")){
            //Hasil server belum punya terjemahan, nama_id dibiarkan kosong.
            Sequel.queryu2("insert into satu_sehat_referensi_profesi_snomed (jenis,kode,nama) values (?,?,?) "+
                    "on duplicate key update nama=values(nama)",
                    3,new String[]{jenis,tbKamar.getValueAt(row,0)+"",tbKamar.getValueAt(row,1)+""});
        }
        dispose();
    }

    public JTable getTable(){
        return tbKamar;
    }

    public void emptTeks(){
        Keyword.setText("");
        tbKamar.clearSelection();
        Valid.tabelKosong(tabMode);
    }

    private void runBackground(Runnable task) {
        if (ceksukses) return;
        if (executor.isShutdown() || executor.isTerminated()) return;
        if (!isDisplayable()) return;

        ceksukses = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            executor.submit(() -> {
                try {
                    task.run();
                } finally {
                    ceksukses = false;
                    SwingUtilities.invokeLater(() -> {
                        if (isDisplayable()) {
                            setCursor(Cursor.getDefaultCursor());
                        }
                    });
                }
            });
        } catch (RejectedExecutionException ex) {
            ceksukses = false;
        }
    }

    @Override
    public void dispose() {
        executor.shutdownNow();
        super.dispose();
    }
}
