/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgJadwal.java
 *
 * Created on May 22, 2010, 10:25:16 PM
 */
package bridging;

import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import kepegawaian.*;

public class FingerspotJadwalPegawaiSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private volatile boolean ceksukses = false;
    private int i = 0;
    private YearMonth ym = YearMonth.now();

    /**
     * Creates new form DlgJadwal
     *
     * @param parent
     * @param modal
     */
    public FingerspotJadwalPegawaiSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new Object[] {
            "No", "NIK", "Nama", "Pendidikan", "Departemen", "01", "02", "03", "04", "05",
            "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18",
            "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
        }) {
            @Override
            public Class getColumnClass(int columnIndex) {
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column > 4 && column < 5 + ym.lengthOfMonth();
            }
        };
        tbJadwal.setModel(tabMode);

        for (int i = 0; i < tabMode.getColumnCount(); i++) {
            TableColumn column = tbJadwal.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(35);
            } else if (i == 1) {
                column.setPreferredWidth(50);
            } else if (i == 2) {
                column.setPreferredWidth(250);
            } else if (i == 3) {
                column.setPreferredWidth(120);
            } else if (i == 4) {
                column.setPreferredWidth(120);
            } else {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            }
        }

        tbJadwal.setDefaultRenderer(Object.class, new WarnaTable());
        tbJadwal.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbJadwal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        Valid.LoadTahun(ThnCari);
        Valid.loadCombo(Departemen, "nama", "departemen");
        Departemen.addItem("Semua");
        Departemen.setSelectedItem("Semua");

        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbJadwal = new widget.Table();
        jPanel3 = new javax.swing.JPanel();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnHapus = new widget.Button();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        LCount = new widget.Label();
        jLabel7 = new widget.Label();
        panelGlass9 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        panelBiasa1 = new widget.PanelBiasa();
        label11 = new widget.Label();
        ThnCari = new widget.ComboBox();
        BlnCari = new widget.ComboBox();
        label12 = new widget.Label();
        Departemen = new widget.ComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pengaturan Jadwal Masuk Pegawai ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbJadwal.setName("tbJadwal"); // NOI18N
        tbJadwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbJadwalKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbJadwal);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(null);

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('U');
        BtnSimpan.setText("Update");
        BtnSimpan.setToolTipText("Alt+U");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);
        BtnSimpan.setBounds(6, 10, 100, 30);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);
        BtnHapus.setBounds(108, 10, 100, 30);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnPrint);
        BtnPrint.setBounds(414, 10, 100, 30);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);
        BtnKeluar.setBounds(518, 10, 100, 30);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass8.add(LCount);
        LCount.setBounds(310, 15, 90, 23);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(65, 23));
        panelGlass8.add(jLabel7);
        jLabel7.setBounds(225, 15, 80, 23);

        jPanel3.add(panelGlass8, java.awt.BorderLayout.CENTER);

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass9.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(450, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass9.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('3');
        BtnCari.setToolTipText("Alt+3");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('4');
        BtnAll.setToolTipText("Alt+4");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnAll);

        jPanel3.add(panelGlass9, java.awt.BorderLayout.PAGE_START);

        internalFrame1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panelBiasa1.setName("panelBiasa1"); // NOI18N
        panelBiasa1.setPreferredSize(new java.awt.Dimension(1023, 47));
        panelBiasa1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 10));

        label11.setText("Tahun & Bulan :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(90, 23));
        panelBiasa1.add(label11);

        ThnCari.setName("ThnCari"); // NOI18N
        ThnCari.setPreferredSize(new java.awt.Dimension(85, 23));
        ThnCari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ThnCariItemStateChanged(evt);
            }
        });
        panelBiasa1.add(ThnCari);

        BlnCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BlnCari.setName("BlnCari"); // NOI18N
        BlnCari.setPreferredSize(new java.awt.Dimension(62, 23));
        BlnCari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BlnCariItemStateChanged(evt);
            }
        });
        panelBiasa1.add(BlnCari);

        label12.setText("Departemen :");
        label12.setName("label12"); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(120, 23));
        panelBiasa1.add(label12);

        Departemen.setName("Departemen"); // NOI18N
        Departemen.setPreferredSize(new java.awt.Dimension(230, 23));
        Departemen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DepartemenItemStateChanged(evt);
            }
        });
        panelBiasa1.add(Departemen);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed

        for (i = 0; i < tabMode.getRowCount(); i++) {
            Sequel.menyimpan2("jadwal_pegawai", "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", 34,
                new String[] {
                    tabMode.getValueAt(i, 1).toString(),
                    ThnCari.getSelectedItem().toString(),
                    BlnCari.getSelectedItem().toString(),
                    tabMode.getValueAt(i, 5).toString(),
                    tabMode.getValueAt(i, 6).toString(),
                    tabMode.getValueAt(i, 7).toString(),
                    tabMode.getValueAt(i, 8).toString(),
                    tabMode.getValueAt(i, 9).toString(), tabMode.getValueAt(i, 10).toString(),
                    tabMode.getValueAt(i, 11).toString(), tabMode.getValueAt(i, 12).toString(), tabMode.getValueAt(i, 13).toString(),
                    tabMode.getValueAt(i, 14).toString(), tabMode.getValueAt(i, 15).toString(), tabMode.getValueAt(i, 16).toString(),
                    tabMode.getValueAt(i, 17).toString(), tabMode.getValueAt(i, 18).toString(), tabMode.getValueAt(i, 19).toString(),
                    tabMode.getValueAt(i, 20).toString(), tabMode.getValueAt(i, 21).toString(), tabMode.getValueAt(i, 22).toString(),
                    tabMode.getValueAt(i, 23).toString(), tabMode.getValueAt(i, 24).toString(), tabMode.getValueAt(i, 25).toString(),
                    tabMode.getValueAt(i, 26).toString(), tabMode.getValueAt(i, 27).toString(), tabMode.getValueAt(i, 28).toString(),
                    tabMode.getValueAt(i, 29).toString(), tabMode.getValueAt(i, 30).toString(), tabMode.getValueAt(i, 31).toString(),
                    tabMode.getValueAt(i, 32).toString(), tabMode.getValueAt(i, 33).toString(), tabMode.getValueAt(i, 34).toString(),
                    tabMode.getValueAt(i, 35).toString()
                },
                "id=? and tahun=? and bulan=?", "h1=?,h2=?,h3=?,h4=?,h5=?,h6=?,h7=?,h8=?,h9=?,h10=?,h11=?,h12=?,h13=?,h14=?," +
                "h15=?,h16=?,h17=?,h18=?,h19=?,h20=?,h21=?,h22=?,h23=?,h24=?,h25=?,h26=?,h27=?,h28=?,h29=?,h30=?,h31=?", 34,
                new String[] {
                    tabMode.getValueAt(i, 5).toString(),
                    tabMode.getValueAt(i, 6).toString(),
                    tabMode.getValueAt(i, 7).toString(),
                    tabMode.getValueAt(i, 8).toString(),
                    tabMode.getValueAt(i, 9).toString(), tabMode.getValueAt(i, 10).toString(),
                    tabMode.getValueAt(i, 11).toString(), tabMode.getValueAt(i, 12).toString(), tabMode.getValueAt(i, 13).toString(),
                    tabMode.getValueAt(i, 14).toString(), tabMode.getValueAt(i, 15).toString(), tabMode.getValueAt(i, 16).toString(),
                    tabMode.getValueAt(i, 17).toString(), tabMode.getValueAt(i, 18).toString(), tabMode.getValueAt(i, 19).toString(),
                    tabMode.getValueAt(i, 20).toString(), tabMode.getValueAt(i, 21).toString(), tabMode.getValueAt(i, 22).toString(),
                    tabMode.getValueAt(i, 23).toString(), tabMode.getValueAt(i, 24).toString(), tabMode.getValueAt(i, 25).toString(),
                    tabMode.getValueAt(i, 26).toString(), tabMode.getValueAt(i, 27).toString(), tabMode.getValueAt(i, 28).toString(),
                    tabMode.getValueAt(i, 29).toString(), tabMode.getValueAt(i, 30).toString(), tabMode.getValueAt(i, 31).toString(),
                    tabMode.getValueAt(i, 32).toString(), tabMode.getValueAt(i, 33).toString(), tabMode.getValueAt(i, 34).toString(),
                    tabMode.getValueAt(i, 35).toString(), tabMode.getValueAt(i, 1).toString(), ThnCari.getSelectedItem().toString(),
                    BlnCari.getSelectedItem().toString()
                });
        }

        JOptionPane.showMessageDialog(null, "Proses selesai...!!!!");
        tampilSmc();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnSimpanActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnKeluar, BtnHapus);
        }
    }//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        if (tabMode.getRowCount() != 0) {
            if (tbJadwal.getSelectedRow() != -1) {
                Sequel.queryu2("delete from jadwal_pegawai where id=? and tahun=? and bulan=?", 3, new String[] {
                    tabMode.getValueAt(tbJadwal.getSelectedRow(), 1).toString(),
                    ThnCari.getSelectedItem().toString(), BlnCari.getSelectedItem().toString()
                });
                tampilSmc();
            }
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnHapusActionPerformed(null);
        } else {
            Valid.pindah(evt, BtnSimpan, BtnPrint);
        }
    }//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnPrint, TCari);
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        if (ceksukses) {
            JOptionPane.showMessageDialog(null, "Proses loading data belum selesai, silahkan tunggu hingga proses loading selesai...!!!!");
            return;
        }
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
        } else if (tabMode.getRowCount() != 0) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(new File("file2.css")))) {
                    bw.write(".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.head td{border-right: 1px solid #777777;font: 8.5px tahoma;height:10px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.isi a{text-decoration:none;color:#8b9b95;padding:0 0 0 0px;font-family: Tahoma;font-size: 8.5px;}.isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}.isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}");
                    bw.flush();
                }
                String pilihan = (String) JOptionPane.showInputDialog(null, "Silahkan pilih laporan..!", "Pilihan Cetak", JOptionPane.QUESTION_MESSAGE, null, new Object[] {
                    "Laporan 1 (HTML)", "Laporan 2 (WPS)", "Laporan 3 (CSV)", "Laporan 4 (XLSX)", "Laporan 5 (Jasper)"
                }, "Laporan 5 (Jasper)");
                switch (pilihan) {
                    case "Laporan 1 (HTML)":
                        Valid.exportHtmlSmc("JadwalPegawai.html", "Jadwal Masuk Pegawai", tbJadwal);
                        break;
                    case "Laporan 2 (WPS)":
                        Valid.exportWPSSmc("JadwalPegawai.wps", "Jadwal Masuk Pegawai", tbJadwal);
                        break;
                    case "Laporan 3 (CSV)":
                        Valid.exportCSVSmc("JadwalPegawai.csv", tbJadwal);
                        break;
                    case "Laporan 4 (XLSX)":
                        Valid.exportXlsxSmc("JadwalPegawai.xlsx", tbJadwal);
                        break;
                    case "Laporan 5 (Jasper)":
                        break;
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnPrintActionPerformed(null);
        } else {
            //Valid.pindah(evt, BtnEdit, BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampilSmc();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {
            Valid.pindah(evt, TCari, BtnAll);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampilSmc();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            TCari.setText("");
            tampilSmc();
        } else {
            Valid.pindah(evt, BtnCari, BtnKeluar);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampilSmc();
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampilSmc();
                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampilSmc();
                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {
                        tampilSmc();
                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void tbJadwalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJadwalKeyPressed
        if (tabMode.getRowCount() != 0) {
            if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                DlgJamMasuk jammasuk = new DlgJamMasuk(null, false);
                jammasuk.addWindowListener(new WindowListener() {
                    @Override
                    public void windowOpened(WindowEvent e) {
                    }

                    @Override
                    public void windowClosing(WindowEvent e) {
                    }

                    @Override
                    public void windowClosed(WindowEvent e) {
                        if (jammasuk.getTable().getSelectedRow() != -1) {
                            if (tbJadwal.getSelectedColumn() > 4) {
                                tabMode.setValueAt(jammasuk.getTable().getValueAt(jammasuk.getTable().getSelectedRow(), 1).toString(), tbJadwal.getSelectedRow(), tbJadwal.getSelectedColumn());
                            }
                        }
                        tbJadwal.requestFocus();
                    }

                    @Override
                    public void windowIconified(WindowEvent e) {
                    }

                    @Override
                    public void windowDeiconified(WindowEvent e) {
                    }

                    @Override
                    public void windowActivated(WindowEvent e) {
                    }

                    @Override
                    public void windowDeactivated(WindowEvent e) {
                    }
                });

                jammasuk.getTable().addKeyListener(new KeyListener() {
                    @Override
                    public void keyTyped(KeyEvent e) {
                    }

                    @Override
                    public void keyPressed(KeyEvent e) {
                        if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                            jammasuk.dispose();
                        }
                    }

                    @Override
                    public void keyReleased(KeyEvent e) {
                    }
                });
                jammasuk.isCek();
                jammasuk.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight());
                jammasuk.setLocationRelativeTo(internalFrame1);
                jammasuk.setVisible(true);
            } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                tabMode.setValueAt("", tbJadwal.getSelectedRow(), tbJadwal.getSelectedColumn());
            }
        }
    }//GEN-LAST:event_tbJadwalKeyPressed

    private void BlnCariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BlnCariItemStateChanged
        if (this.isActive() == true) {
            tampilSmc();
        }
    }//GEN-LAST:event_BlnCariItemStateChanged

    private void ThnCariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ThnCariItemStateChanged
        if (this.isActive() == true) {
            System.out.println("coba");
            tampilSmc();
        }
    }//GEN-LAST:event_ThnCariItemStateChanged

    private void DepartemenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DepartemenItemStateChanged
        if (this.isActive() == true) {
            tampilSmc();
        }
    }//GEN-LAST:event_DepartemenItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            FingerspotJadwalPegawaiSMC dialog = new FingerspotJadwalPegawaiSMC(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.ComboBox BlnCari;
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.Button BtnSimpan;
    private widget.ComboBox Departemen;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.ComboBox ThnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private javax.swing.JPanel jPanel3;
    private widget.Label label11;
    private widget.Label label12;
    private widget.PanelBiasa panelBiasa1;
    private widget.panelisi panelGlass8;
    private widget.panelisi panelGlass9;
    private widget.Table tbJadwal;
    // End of variables declaration//GEN-END:variables

    /*
    private void tampil() {
        Object[] row={"No","ID","Nama","Pendidikan","Departemen",
            "1("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),1)+")",
            "2("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),2)+")",
            "3("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),3)+")",
            "4("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),4)+")",
            "5("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),5)+")",
            "6("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),6)+")",
            "7("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),7)+")",
            "8("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),8)+")",
            "9("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),9)+")",
            "10("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),10)+")",
            "11("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),11)+")",
            "12("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),12)+")",
            "13("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),13)+")",
            "14("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),14)+")",
            "15("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),15)+")",
            "16("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),16)+")",
            "17("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),17)+")",
            "18("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),18)+")",
            "19("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),19)+")",
            "20("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),20)+")",
            "21("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),21)+")",
            "22("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),22)+")",
            "23("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),23)+")",
            "24("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),24)+")",
            "25("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),25)+")",
            "26("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),26)+")",
            "27("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),27)+")",
            "28("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),28)+")",
            "29("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),29)+")",
            "30("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),30)+")",
            "31("+konversi(Integer.parseInt(ThnCari.getSelectedItem().toString()),Integer.parseInt(BlnCari.getSelectedItem().toString()),31)+")"
        };
        tabMode=new DefaultTableModel(null,row){
             @Override public boolean isCellEditable(int rowIndex, int colIndex){
                boolean a = false;
                if (colIndex==0) {
                    a=true;
                }
                return a;
             }
             Class[] types = new Class[] {
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        tbJadwal.setModel(tabMode);

        for (int i = 0; i < 36; i++) {
            TableColumn column = tbJadwal.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(35);
            }else if(i==1){
                column.setPreferredWidth(50);
            }else if(i==2){
                column.setPreferredWidth(250);
            }else if(i==3){
                column.setPreferredWidth(120);
            }else if(i==4){
                column.setPreferredWidth(120);
            }else{
                column.setPreferredWidth(75);
            }
        }
        tbJadwal.setDefaultRenderer(Object.class, new WarnaTable());

        Valid.tabelKosong(tabMode);
        try{
            ps=koneksi.prepareStatement(
                    "select pegawai.id,pegawai.nik,pegawai.nama,pegawai.pendidikan,departemen.nama as departemen from pegawai inner join departemen "+
                    "on pegawai.departemen=departemen.dep_id where  pegawai.stts_aktif<>'KELUAR' and departemen.nama like ? and pegawai.nik like ? or "+
                    " pegawai.stts_aktif<>'KELUAR' and departemen.nama like ? and pegawai.nama like ? order by pegawai.nama");
            try {
                ps.setString(1,"%"+Departemen.getSelectedItem().toString().replaceAll("Semua","")+"%");
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                ps.setString(3,"%"+Departemen.getSelectedItem().toString().replaceAll("Semua","")+"%");
                ps.setString(4,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    h1="";h2="";h3="";h4="";h5="";h6="";h7="";h8="";h9="";h10="";h11="";h12="";h13="";
                    h14="";h15="";h16="";h17="";h18="";h19="";h20="";h21="";h22="";h23="";h24="";
                    h25="";h26="";h27="";h28="";h29="";h30="";h31="";
                    ps2=koneksi.prepareStatement("select jadwal_pegawai.h1,jadwal_pegawai.h2,jadwal_pegawai.h3,jadwal_pegawai.h4,jadwal_pegawai.h5,"+
                        "jadwal_pegawai.h6,jadwal_pegawai.h7,jadwal_pegawai.h8,jadwal_pegawai.h9,jadwal_pegawai.h10,"+
                        "jadwal_pegawai.h11,jadwal_pegawai.h12,jadwal_pegawai.h13,jadwal_pegawai.h14,jadwal_pegawai.h15,"+
                        "jadwal_pegawai.h16,jadwal_pegawai.h17,jadwal_pegawai.h18,jadwal_pegawai.h19,jadwal_pegawai.h20,"+
                        "jadwal_pegawai.h21,jadwal_pegawai.h22,jadwal_pegawai.h23,jadwal_pegawai.h24,jadwal_pegawai.h25,"+
                        "jadwal_pegawai.h26,jadwal_pegawai.h27,jadwal_pegawai.h28,jadwal_pegawai.h29,jadwal_pegawai.h30,"+
                        "jadwal_pegawai.h31 from jadwal_pegawai where jadwal_pegawai.id=? and jadwal_pegawai.tahun=? and jadwal_pegawai.bulan=?  ");
                    try {
                        ps2.setString(1,rs.getString("id"));
                        ps2.setString(2,ThnCari.getSelectedItem().toString());
                        ps2.setString(3,BlnCari.getSelectedItem().toString());
                        rs2=ps2.executeQuery();
                        if(rs2.next()){
                            h1=rs2.getString("h1");
                            h2=rs2.getString("h2");
                            h3=rs2.getString("h3");
                            h4=rs2.getString("h4");
                            h5=rs2.getString("h5");
                            h6=rs2.getString("h6");
                            h7=rs2.getString("h7");
                            h8=rs2.getString("h8");
                            h9=rs2.getString("h9");
                            h10=rs2.getString("h10");
                            h11=rs2.getString("h11");
                            h12=rs2.getString("h12");
                            h13=rs2.getString("h13");
                            h14=rs2.getString("h14");
                            h15=rs2.getString("h15");
                            h16=rs2.getString("h16");
                            h17=rs2.getString("h17");
                            h18=rs2.getString("h18");
                            h19=rs2.getString("h19");
                            h20=rs2.getString("h20");
                            h21=rs2.getString("h21");
                            h22=rs2.getString("h22");
                            h23=rs2.getString("h23");
                            h24=rs2.getString("h24");
                            h25=rs2.getString("h25");
                            h26=rs2.getString("h26");
                            h27=rs2.getString("h27");
                            h28=rs2.getString("h28");
                            h29=rs2.getString("h29");
                            h30=rs2.getString("h30");
                            h31=rs2.getString("h31");
                        }
                    } catch (Exception e) {
                        System.out.println("Notif : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }

                    tabMode.addRow(new Object[]{
                        " "+i+".",rs.getString("id"),rs.getString("nama"),rs.getString("pendidikan"),rs.getString("departemen"),
                        h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13,h14,h15,h16,h17,h18,h19,h20,h21,h22,h23,h24,h25,h26,h27,h28,h29,h30,h31
                    });
                    i++;
                }
            } catch (Exception e) {
                System.out.println("Notif : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());
    }
    */
    public void isCek() {
        BtnSimpan.setEnabled(akses.getjadwal_pegawai());
        BtnHapus.setEnabled(akses.getjadwal_pegawai());
    }

    private void tampilSmc() {
        if (!ceksukses) {
            ceksukses = true;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Valid.tabelKosongSmc(tabMode);

            ym = YearMonth.parse(ThnCari.getSelectedItem().toString() + "-" + BlnCari.getSelectedItem().toString());
            final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd (EEEE)", new Locale("id", "ID"));
            final LinkedList<LocalDate> days = IntStream.rangeClosed(1, ym.lengthOfMonth())
                .collect(LinkedList::new, (list, day) -> list.add(ym.atDay(day)), LinkedList::addAll);

            int i = 5;
            for (LocalDate day : days) {
                TableColumn column = tbJadwal.getColumnModel().getColumn(i++);
                column.setHeaderValue(dtf.format(day).toUpperCase());
                column.setMinWidth(0);
                column.setMaxWidth(Integer.MAX_VALUE);
                column.setPreferredWidth(75);
            }

            for (; i < tabMode.getColumnCount(); i++) {
                TableColumn column = tbJadwal.getColumnModel().getColumn(i);
                column.setHeaderValue("");
                column.setMinWidth(0);
                column.setMaxWidth(0);
                column.setPreferredWidth(0);
            }

            tbJadwal.repaint();

            new SwingWorker<Void, Object[]>() {
                final String departemen = Departemen.getSelectedItem().toString();
                final String cari = TCari.getText().trim();

                @Override
                protected Void doInBackground() throws Exception {
                    try (PreparedStatement ps = koneksi.prepareStatement(
                        "select pegawai.id, pegawai.nik, pegawai.nama, pegawai.pendidikan, departemen.nama as departemen, ifnull(jadwal_pegawai.h1, '') as h1, ifnull(jadwal_pegawai.h2, '') as h2, ifnull(jadwal_pegawai.h3, '') as h3, " +
                        "ifnull(jadwal_pegawai.h4, '') as h4, ifnull(jadwal_pegawai.h5, '') as h5, ifnull(jadwal_pegawai.h6, '') as h6, ifnull(jadwal_pegawai.h7, '') as h7, ifnull(jadwal_pegawai.h8, '') as h8, ifnull(jadwal_pegawai.h9, " +
                        "'') as h9, ifnull(jadwal_pegawai.h10, '') as h10, ifnull(jadwal_pegawai.h11, '') as h11, ifnull(jadwal_pegawai.h12, '') as h12, ifnull(jadwal_pegawai.h13, '') as h13, ifnull(jadwal_pegawai.h14, '') as h14, " +
                        "ifnull(jadwal_pegawai.h15, '') as h15, ifnull(jadwal_pegawai.h16, '') as h16, ifnull(jadwal_pegawai.h17, '') as h17, ifnull(jadwal_pegawai.h18, '') as h18, ifnull(jadwal_pegawai.h19, '') as h19, " +
                        "ifnull(jadwal_pegawai.h20, '') as h20, ifnull(jadwal_pegawai.h21, '') as h21, ifnull(jadwal_pegawai.h22, '') as h22, ifnull(jadwal_pegawai.h23, '') as h23, ifnull(jadwal_pegawai.h24, '') as h24, " +
                        "ifnull(jadwal_pegawai.h25, '') as h25, ifnull(jadwal_pegawai.h26, '') as h26, ifnull(jadwal_pegawai.h27, '') as h27, ifnull(jadwal_pegawai.h28, '') as h28, ifnull(jadwal_pegawai.h29, '') as h29, " +
                        "ifnull(jadwal_pegawai.h30, '') as h30, ifnull(jadwal_pegawai.h31, '') as h31 from pegawai inner join departemen on pegawai.departemen = departemen.dep_id left join jadwal_pegawai on pegawai.id = " +
                        "jadwal_pegawai.id where pegawai.stts_aktif != 'KELUAR' " + (departemen.equals("Semua") ? "" : "and departemen.nama = ? ") + (cari.isBlank() ? "" : "and (pegawai.nik like ? or pegawai.nama like ? " +
                        "or departemen.nama like ?) ") + "order by pegawai.nama"
                    )) {
                        int p = 0;
                        if (!departemen.equals("Semua")) {
                            ps.setString(++p, departemen);
                        }
                        if (!cari.isBlank()) {
                            ps.setString(++p, "%" + cari + "%");
                            ps.setString(++p, "%" + cari + "%");
                            ps.setString(++p, "%" + cari + "%");
                        }
                        try (ResultSet rs = ps.executeQuery()) {
                            int i = 1;
                            while (rs.next()) {
                                publish(new Object[] {
                                    (i++), rs.getString("nik"), rs.getString("nama"), rs.getString("pendidikan"), rs.getString("departemen"), rs.getString("h1"), rs.getString("h2"), rs.getString("h3"), rs.getString("h4"),
                                    rs.getString("h5"), rs.getString("h6"), rs.getString("h7"), rs.getString("h8"), rs.getString("h9"), rs.getString("h10"), rs.getString("h11"), rs.getString("h12"), rs.getString("h13"),
                                    rs.getString("h14"), rs.getString("h15"), rs.getString("h16"), rs.getString("h17"), rs.getString("h18"), rs.getString("h19"), rs.getString("h20"), rs.getString("h21"), rs.getString("h22"),
                                    rs.getString("h23"), rs.getString("h24"), rs.getString("h25"), rs.getString("h26"), rs.getString("h27"), rs.getString("h28"), rs.getString("h29"), rs.getString("h30"), rs.getString("h31")
                                });
                            }
                        }
                    }
                    return null;
                }

                @Override
                protected void process(List<Object[]> chunks) {
                    chunks.forEach(tabMode::addRow);
                }

                @Override
                protected void done() {
                    try {
                        get();
                    } catch (Exception e) {
                        System.out.println("Notif : " + e);
                    }
                    tabMode.fireTableDataChanged();
                    LCount.setText(tabMode.getRowCount() + "");
                    FingerspotJadwalPegawaiSMC.this.setCursor(Cursor.getDefaultCursor());
                    ceksukses = false;
                }
            }.execute();
        }
    }
}
