package bridging;

import ipsrs.*;
import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import inventory.DlgCariSatuan;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import restore.DlgRestoreIPSRSBarang;

public final class INACBGDataKelahiranSMC extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private volatile boolean ceksukses = false;

    /**
     * Creates new form DlgJnsPerawatan
     *
     * @param parent
     * @param modal
     */
    public INACBGDataKelahiranSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabMode = new DefaultTableModel(null, new String[] {"Kode Barang", "Nama Barang", "Satuan", "Jenis", "Stok", "Harga"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
            @Override
            public Class getColumnClass(int columnIndex) {
                return String.class;
            }
        };
        tbJnsPerawatan.setModel(tabMode);

        //tbObat.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbObat.getBackground()));
        tbJnsPerawatan.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbJnsPerawatan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 6; i++) {
            TableColumn column = tbJnsPerawatan.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(100);
            } else if (i == 1) {
                column.setPreferredWidth(220);
            } else if (i == 2) {
                column.setPreferredWidth(150);
            } else if (i == 3) {
                column.setPreferredWidth(120);
            } else if (i == 4) {
                column.setPreferredWidth(60);
            } else if (i == 5) {
                column.setPreferredWidth(120);
            }
        }
        tbJnsPerawatan.setDefaultRenderer(Object.class, new WarnaTable());

        // kode_brng.setDocument(new batasInput((byte) 15).getKata(kode_brng));
        // nama_brng.setDocument(new batasInput((byte) 80).getKata(nama_brng));
        // kode_sat.setDocument(new batasInput((byte) 4).getKata(kode_sat));
        // stok.setDocument(new batasInput((byte) 10).getKata(stok));
        // harga.setDocument(new batasInput((byte) 20).getKata(harga));
        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));
        TCari.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbJnsPerawatan = new widget.Table();
        jPanel3 = new javax.swing.JPanel();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnBatal = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass9 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        PanelInput = new javax.swing.JPanel();
        jLabel115 = new widget.Label();
        urutanKelahiran = new widget.TextBox();
        jLabel116 = new widget.Label();
        caraLahir = new widget.ComboBox();
        jLabel118 = new widget.Label();
        waktuKelahiran = new widget.Tanggal();
        jLabel127 = new widget.Label();
        cmbJamKelahiran = new widget.ComboBox();
        cmbMenitKelahiran = new widget.ComboBox();
        cmbDetikKelahiran = new widget.ComboBox();
        jLabel117 = new widget.Label();
        letakJanin = new widget.ComboBox();
        jLabel119 = new widget.Label();
        kondisiLahir = new widget.ComboBox();
        jLabel120 = new widget.Label();
        useManual = new widget.ComboBox();
        useForcep = new widget.ComboBox();
        jLabel121 = new widget.Label();
        jLabel122 = new widget.Label();
        useVacuum = new widget.ComboBox();
        jLabel123 = new widget.Label();
        spesimenSHKDiambil = new widget.ComboBox();
        jLabel125 = new widget.Label();
        lokasiSpesimen = new widget.ComboBox();
        jLabel124 = new widget.Label();
        waktuPengambilanSHK = new widget.Tanggal();
        jLabel128 = new widget.Label();
        cmbJamSpesimen = new widget.ComboBox();
        cmbMenitSpesimen = new widget.ComboBox();
        cmbDetikSpesimen = new widget.ComboBox();
        jLabel126 = new widget.Label();
        alasanSpesimenTidakDiambil = new widget.ComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Barang Non Medis & Penunjang ( Lab & RO ) ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbJnsPerawatan.setAutoCreateRowSorter(true);
        tbJnsPerawatan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbJnsPerawatan.setName("tbJnsPerawatan"); // NOI18N
        Scroll.setViewportView(tbJnsPerawatan);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 100));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnBatal);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnHapus);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnEdit);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        jPanel3.add(panelGlass8, java.awt.BorderLayout.CENTER);

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass9.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(450, 23));
        panelGlass9.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 23));
        panelGlass9.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass9.add(LCount);

        jPanel3.add(panelGlass9, java.awt.BorderLayout.PAGE_START);

        internalFrame1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(192, 283));
        PanelInput.setLayout(null);

        jLabel115.setText("Urutan Kelahiran :");
        jLabel115.setName("jLabel115"); // NOI18N
        jLabel115.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel115);
        jLabel115.setBounds(0, 70, 107, 23);

        urutanKelahiran.setName("urutanKelahiran"); // NOI18N
        urutanKelahiran.setPreferredSize(new java.awt.Dimension(50, 23));
        PanelInput.add(urutanKelahiran);
        urutanKelahiran.setBounds(110, 70, 50, 23);

        jLabel116.setText("Cara Kelahiran :");
        jLabel116.setName("jLabel116"); // NOI18N
        jLabel116.setPreferredSize(new java.awt.Dimension(90, 23));
        PanelInput.add(jLabel116);
        jLabel116.setBounds(189, 70, 90, 23);

        caraLahir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vaginal", "Sectio Caesarean" }));
        caraLahir.setMinimumSize(new java.awt.Dimension(100, 23));
        caraLahir.setName("caraLahir"); // NOI18N
        caraLahir.setPreferredSize(new java.awt.Dimension(180, 23));
        PanelInput.add(caraLahir);
        caraLahir.setBounds(282, 70, 180, 23);

        jLabel118.setText("Waktu Kelahiran :");
        jLabel118.setName("jLabel118"); // NOI18N
        jLabel118.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel118);
        jLabel118.setBounds(0, 100, 107, 23);

        waktuKelahiran.setDisplayFormat("dd-MM-yyyy");
        waktuKelahiran.setName("waktuKelahiran"); // NOI18N
        waktuKelahiran.setPreferredSize(new java.awt.Dimension(106, 23));
        PanelInput.add(waktuKelahiran);
        waktuKelahiran.setBounds(110, 100, 106, 23);

        jLabel127.setText("Jam :");
        jLabel127.setName("jLabel127"); // NOI18N
        jLabel127.setPreferredSize(new java.awt.Dimension(48, 23));
        PanelInput.add(jLabel127);
        jLabel127.setBounds(219, 100, 48, 23);

        cmbJamKelahiran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbJamKelahiran.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbJamKelahiran.setName("cmbJamKelahiran"); // NOI18N
        cmbJamKelahiran.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbJamKelahiran);
        cmbJamKelahiran.setBounds(270, 100, 62, 23);

        cmbMenitKelahiran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMenitKelahiran.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbMenitKelahiran.setName("cmbMenitKelahiran"); // NOI18N
        cmbMenitKelahiran.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbMenitKelahiran);
        cmbMenitKelahiran.setBounds(335, 100, 62, 23);

        cmbDetikKelahiran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbDetikKelahiran.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbDetikKelahiran.setName("cmbDetikKelahiran"); // NOI18N
        cmbDetikKelahiran.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbDetikKelahiran);
        cmbDetikKelahiran.setBounds(400, 100, 62, 23);

        jLabel117.setText("Letak Janin :");
        jLabel117.setName("jLabel117"); // NOI18N
        jLabel117.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel117);
        jLabel117.setBounds(0, 130, 107, 23);

        letakJanin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Kepala", "Sungsang", "Lintang / Oblique" }));
        letakJanin.setMinimumSize(new java.awt.Dimension(100, 23));
        letakJanin.setName("letakJanin"); // NOI18N
        letakJanin.setPreferredSize(new java.awt.Dimension(184, 23));
        PanelInput.add(letakJanin);
        letakJanin.setBounds(110, 130, 184, 23);

        jLabel119.setText("Kondisi :");
        jLabel119.setName("jLabel119"); // NOI18N
        jLabel119.setPreferredSize(new java.awt.Dimension(52, 23));
        PanelInput.add(jLabel119);
        jLabel119.setBounds(297, 130, 52, 23);

        kondisiLahir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Hidup", "Meninggal" }));
        kondisiLahir.setMinimumSize(new java.awt.Dimension(100, 23));
        kondisiLahir.setName("kondisiLahir"); // NOI18N
        kondisiLahir.setPreferredSize(new java.awt.Dimension(110, 23));
        PanelInput.add(kondisiLahir);
        kondisiLahir.setBounds(352, 130, 110, 23);

        jLabel120.setText("Bantuan Manual :");
        jLabel120.setName("jLabel120"); // NOI18N
        jLabel120.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel120);
        jLabel120.setBounds(0, 160, 107, 23);

        useManual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0. Tidak", "1. Ya" }));
        useManual.setMinimumSize(new java.awt.Dimension(100, 23));
        useManual.setName("useManual"); // NOI18N
        useManual.setPreferredSize(new java.awt.Dimension(80, 23));
        PanelInput.add(useManual);
        useManual.setBounds(110, 160, 80, 23);

        useForcep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0. Tidak", "1. Ya" }));
        useForcep.setMinimumSize(new java.awt.Dimension(100, 23));
        useForcep.setName("useForcep"); // NOI18N
        useForcep.setPreferredSize(new java.awt.Dimension(80, 23));
        PanelInput.add(useForcep);
        useForcep.setBounds(246, 160, 80, 23);

        jLabel121.setText("Forcep :");
        jLabel121.setName("jLabel121"); // NOI18N
        jLabel121.setPreferredSize(new java.awt.Dimension(50, 23));
        PanelInput.add(jLabel121);
        jLabel121.setBounds(193, 160, 50, 23);

        jLabel122.setText("Vacuum :");
        jLabel122.setName("jLabel122"); // NOI18N
        jLabel122.setPreferredSize(new java.awt.Dimension(50, 23));
        PanelInput.add(jLabel122);
        jLabel122.setBounds(329, 160, 50, 23);

        useVacuum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "0. Tidak", "1. Ya" }));
        useVacuum.setMinimumSize(new java.awt.Dimension(100, 23));
        useVacuum.setName("useVacuum"); // NOI18N
        useVacuum.setPreferredSize(new java.awt.Dimension(80, 23));
        PanelInput.add(useVacuum);
        useVacuum.setBounds(382, 160, 80, 23);

        jLabel123.setText("Spesimen SHK :");
        jLabel123.setName("jLabel123"); // NOI18N
        jLabel123.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel123);
        jLabel123.setBounds(0, 190, 107, 23);

        spesimenSHKDiambil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Diambil", "Tidak Diambil" }));
        spesimenSHKDiambil.setMinimumSize(new java.awt.Dimension(100, 23));
        spesimenSHKDiambil.setName("spesimenSHKDiambil"); // NOI18N
        spesimenSHKDiambil.setPreferredSize(new java.awt.Dimension(215, 23));
        spesimenSHKDiambil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                spesimenSHKDiambilItemStateChanged(evt);
            }
        });
        PanelInput.add(spesimenSHKDiambil);
        spesimenSHKDiambil.setBounds(110, 190, 215, 23);

        jLabel125.setText("Lokasi :");
        jLabel125.setName("jLabel125"); // NOI18N
        jLabel125.setPreferredSize(new java.awt.Dimension(47, 23));
        PanelInput.add(jLabel125);
        jLabel125.setBounds(328, 190, 47, 23);

        lokasiSpesimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Tumit", "Vena" }));
        lokasiSpesimen.setMinimumSize(new java.awt.Dimension(100, 23));
        lokasiSpesimen.setName("lokasiSpesimen"); // NOI18N
        lokasiSpesimen.setPreferredSize(new java.awt.Dimension(84, 23));
        PanelInput.add(lokasiSpesimen);
        lokasiSpesimen.setBounds(378, 190, 84, 23);

        jLabel124.setText("Waktu Pengambilan :");
        jLabel124.setName("jLabel124"); // NOI18N
        jLabel124.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel124);
        jLabel124.setBounds(0, 220, 107, 23);

        waktuPengambilanSHK.setDisplayFormat("dd-MM-yyyy");
        waktuPengambilanSHK.setName("waktuPengambilanSHK"); // NOI18N
        waktuPengambilanSHK.setPreferredSize(new java.awt.Dimension(106, 23));
        PanelInput.add(waktuPengambilanSHK);
        waktuPengambilanSHK.setBounds(110, 220, 106, 23);

        jLabel128.setText("Jam :");
        jLabel128.setName("jLabel128"); // NOI18N
        jLabel128.setPreferredSize(new java.awt.Dimension(48, 23));
        PanelInput.add(jLabel128);
        jLabel128.setBounds(219, 220, 48, 23);

        cmbJamSpesimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbJamSpesimen.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbJamSpesimen.setName("cmbJamSpesimen"); // NOI18N
        cmbJamSpesimen.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbJamSpesimen);
        cmbJamSpesimen.setBounds(270, 220, 62, 23);

        cmbMenitSpesimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMenitSpesimen.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbMenitSpesimen.setName("cmbMenitSpesimen"); // NOI18N
        cmbMenitSpesimen.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbMenitSpesimen);
        cmbMenitSpesimen.setBounds(335, 220, 62, 23);

        cmbDetikSpesimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbDetikSpesimen.setMinimumSize(new java.awt.Dimension(62, 23));
        cmbDetikSpesimen.setName("cmbDetikSpesimen"); // NOI18N
        cmbDetikSpesimen.setPreferredSize(new java.awt.Dimension(62, 23));
        PanelInput.add(cmbDetikSpesimen);
        cmbDetikSpesimen.setBounds(400, 220, 62, 23);

        jLabel126.setText("Alasan Tak Diambil :");
        jLabel126.setName("jLabel126"); // NOI18N
        jLabel126.setPreferredSize(new java.awt.Dimension(107, 23));
        PanelInput.add(jLabel126);
        jLabel126.setBounds(0, 250, 107, 23);

        alasanSpesimenTidakDiambil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Tidak Dapat Dilakukan", "Akses Sulit" }));
        alasanSpesimenTidakDiambil.setMinimumSize(new java.awt.Dimension(100, 23));
        alasanSpesimenTidakDiambil.setName("alasanSpesimenTidakDiambil"); // NOI18N
        alasanSpesimenTidakDiambil.setPreferredSize(new java.awt.Dimension(157, 23));
        PanelInput.add(alasanSpesimenTidakDiambil);
        alasanSpesimenTidakDiambil.setBounds(110, 250, 157, 23);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        //
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        //
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        //
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        //
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        //
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        //
    }//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        spesimenSHKDiambil.setSelectedIndex(0);
        if (koneksiDB.CARICEPAT().equals("aktif")) {
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {

                    }
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {

                    }
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    if (TCari.getText().length() > 2) {

                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void spesimenSHKDiambilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_spesimenSHKDiambilItemStateChanged
        if (spesimenSHKDiambil.getSelectedIndex() == 1) {
            lokasiSpesimen.setEnabled(true);
            waktuPengambilanSHK.setEnabled(true);
            cmbJamSpesimen.setEnabled(true);
            cmbMenitSpesimen.setEnabled(true);
            cmbDetikSpesimen.setEnabled(true);
            alasanSpesimenTidakDiambil.setEnabled(false);
        } else {
            lokasiSpesimen.setSelectedIndex(0);
            lokasiSpesimen.setEnabled(false);
            waktuPengambilanSHK.setDate(new Date());
            waktuPengambilanSHK.setEnabled(false);
            cmbJamSpesimen.setSelectedIndex(0);
            cmbJamSpesimen.setEnabled(false);
            cmbMenitSpesimen.setSelectedIndex(0);
            cmbMenitSpesimen.setEnabled(false);
            cmbDetikSpesimen.setSelectedIndex(0);
            cmbDetikSpesimen.setEnabled(false);
            alasanSpesimenTidakDiambil.setEnabled(true);
        }
    }//GEN-LAST:event_spesimenSHKDiambilItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnCari;
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.Label LCount;
    private javax.swing.JPanel PanelInput;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.ComboBox alasanSpesimenTidakDiambil;
    private widget.ComboBox caraLahir;
    private widget.ComboBox cmbDetikKelahiran;
    private widget.ComboBox cmbDetikSpesimen;
    private widget.ComboBox cmbJamKelahiran;
    private widget.ComboBox cmbJamSpesimen;
    private widget.ComboBox cmbMenitKelahiran;
    private widget.ComboBox cmbMenitSpesimen;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel115;
    private widget.Label jLabel116;
    private widget.Label jLabel117;
    private widget.Label jLabel118;
    private widget.Label jLabel119;
    private widget.Label jLabel120;
    private widget.Label jLabel121;
    private widget.Label jLabel122;
    private widget.Label jLabel123;
    private widget.Label jLabel124;
    private widget.Label jLabel125;
    private widget.Label jLabel126;
    private widget.Label jLabel127;
    private widget.Label jLabel128;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private javax.swing.JPanel jPanel3;
    private widget.ComboBox kondisiLahir;
    private widget.ComboBox letakJanin;
    private widget.ComboBox lokasiSpesimen;
    private widget.panelisi panelGlass8;
    private widget.panelisi panelGlass9;
    private widget.ComboBox spesimenSHKDiambil;
    private widget.Table tbJnsPerawatan;
    private widget.TextBox urutanKelahiran;
    private widget.ComboBox useForcep;
    private widget.ComboBox useManual;
    private widget.ComboBox useVacuum;
    private widget.Tanggal waktuKelahiran;
    private widget.Tanggal waktuPengambilanSHK;
    // End of variables declaration//GEN-END:variables

    private void tampil() {

    }

    public void emptTeks() {
        // kode_brng.setText("");
        // nama_brng.setText("");
        // kode_sat.setText("");
        // harga.setText("0");
        // nama_sat.setText("");
        // stok.setText("0");
        // kdjenis.setText("");
        // nmjenis.setText("");
        // Valid.autoNomer3("select ifnull(MAX(CONVERT(RIGHT(ipsrsbarang.kode_brng,4),signed)),0) from ipsrsbarang  ", "B", 5, kode_brng);
        tbJnsPerawatan.clearSelection();
    }

    public void onCari() {
        TCari.requestFocus();
    }

    private void getData() {
        if (tbJnsPerawatan.getSelectedRow() != -1) {
            // kode_brng.setText(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 0).toString());
            // nama_brng.setText(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 1).toString());
            // nama_sat.setText(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 2).toString());
            // nmjenis.setText(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 3).toString());
            // stok.setText(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 4).toString());
            // harga.setText(Valid.SetAngka6(Double.parseDouble(tbJnsPerawatan.getValueAt(tbJnsPerawatan.getSelectedRow(), 5).toString())));
            // kode_sat.setText(Sequel.cariIsi("select ipsrsbarang.kode_sat from ipsrsbarang where ipsrsbarang.kode_brng=?", kode_brng.getText()));
            // kdjenis.setText(Sequel.cariIsi("select ipsrsbarang.jenis from ipsrsbarang where ipsrsbarang.kode_brng=?", kode_brng.getText()));
        }
    }

    public JTable getTable() {
        return tbJnsPerawatan;
    }

    public void isCek() {
        BtnSimpan.setEnabled(akses.getipsrs_barang());
        BtnHapus.setEnabled(akses.getipsrs_barang());
        BtnEdit.setEnabled(akses.getipsrs_barang());
        TCari.requestFocus();
    }
}
