package bridging;

import fungsi.akses;
import java.awt.Cursor;

public final class PilihanBridgingBPJSSMC extends javax.swing.JDialog {
    
    private int lebar = 0, tinggi = 0;
    private String noka = "";

    public PilihanBridgingBPJSSMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass6 = new widget.panelisi();
        BtnKeluar = new widget.Button();
        panelGlass7 = new widget.panelisi();
        btnCekBPJSRujukanKartuPCare = new widget.ButtonBig();
        btnCekBPJSRujukanKartuRS1 = new widget.ButtonBig();
        btnCekBPJSKartu = new widget.ButtonBig();
        btnCekBPJSRujukanKartuRS2 = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)), "::[ Pendaftaran Cepat BPJS ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass7.setLayout(new java.awt.GridLayout(0, 2));

        btnCekBPJSRujukanKartuPCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekBPJSRujukanKartuPCare.setText("Pendaftaran Rujukan Pertama");
        btnCekBPJSRujukanKartuPCare.setIconTextGap(0);
        btnCekBPJSRujukanKartuPCare.setName("btnCekBPJSRujukanKartuPCare"); // NOI18N
        btnCekBPJSRujukanKartuPCare.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekBPJSRujukanKartuPCare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBPJSRujukanKartuPCareActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekBPJSRujukanKartuPCare);

        btnCekBPJSRujukanKartuRS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekBPJSRujukanKartuRS1.setText("Pendaftaran Rencana Kontrol");
        btnCekBPJSRujukanKartuRS1.setIconTextGap(0);
        btnCekBPJSRujukanKartuRS1.setName("btnCekBPJSRujukanKartuRS1"); // NOI18N
        btnCekBPJSRujukanKartuRS1.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekBPJSRujukanKartuRS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBPJSRujukanKartuRS1ActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekBPJSRujukanKartuRS1);

        btnCekBPJSKartu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekBPJSKartu.setText("Pendaftaran Kontrol Penunjang");
        btnCekBPJSKartu.setIconTextGap(0);
        btnCekBPJSKartu.setName("btnCekBPJSKartu"); // NOI18N
        btnCekBPJSKartu.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekBPJSKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBPJSKartuActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekBPJSKartu);

        btnCekBPJSRujukanKartuRS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekBPJSRujukanKartuRS2.setText("Cek In MobileJKN");
        btnCekBPJSRujukanKartuRS2.setIconTextGap(0);
        btnCekBPJSRujukanKartuRS2.setName("btnCekBPJSRujukanKartuRS2"); // NOI18N
        btnCekBPJSRujukanKartuRS2.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekBPJSRujukanKartuRS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekBPJSRujukanKartuRS2ActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekBPJSRujukanKartuRS2);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void btnCekBPJSKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBPJSKartuActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        BPJSCekKartu form = new BPJSCekKartu(null, false);
        form.isCek();
        form.SetNoKartu(noka);
        form.setSize(lebar, tinggi);
        form.setLocationRelativeTo(internalFrame1);
        this.dispose();
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnCekBPJSKartuActionPerformed

    private void btnCekBPJSRujukanKartuPCareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBPJSRujukanKartuPCareActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        BPJSCekRujukanKartuPCare form = new BPJSCekRujukanKartuPCare(null, false);
        form.isCek();
        form.SetNoKartu(noka);
        form.setSize(lebar, tinggi);
        form.setLocationRelativeTo(internalFrame1);
        this.dispose();
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnCekBPJSRujukanKartuPCareActionPerformed

    private void btnCekBPJSRujukanKartuRS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBPJSRujukanKartuRS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekBPJSRujukanKartuRS1ActionPerformed

    private void btnCekBPJSRujukanKartuRS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBPJSRujukanKartuRS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekBPJSRujukanKartuRS2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.ButtonBig btnCekBPJSKartu;
    private widget.ButtonBig btnCekBPJSRujukanKartuPCare;
    private widget.ButtonBig btnCekBPJSRujukanKartuRS1;
    private widget.ButtonBig btnCekBPJSRujukanKartuRS2;
    private widget.InternalFrame internalFrame1;
    private widget.panelisi panelGlass6;
    private widget.panelisi panelGlass7;
    // End of variables declaration//GEN-END:variables

    public void setNoKa(String noka) {
        this.noka = noka;
    }
}
