/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgKamar.java
 *
 * Created on May 23, 2010, 12:07:21 AM
 */
package bridging;

import fungsi.akses;
import java.awt.Cursor;

/**
 *
 * @author dosen
 */
public final class PilihanBridgingAsuransi2 extends javax.swing.JDialog {
    private int lebar = 0, tinggi = 0;
    private String noRujukan = "";

    /**
     * Creates new form DlgKamar
     *
     * @param parent
     * @param modal
     */
    public PilihanBridgingAsuransi2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass6 = new widget.panelisi();
        BtnKeluar = new widget.Button();
        panelGlass7 = new widget.panelisi();
        btnCekRujukanPCareBPJS = new widget.ButtonBig();
        btnCekRujukanRSBPJS = new widget.ButtonBig();
        btnCekSuratKontrolBPJS = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pilihan Bridging Asuransi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass7.setLayout(new java.awt.GridLayout(0, 3));

        btnCekRujukanPCareBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekRujukanPCareBPJS.setText("Cek Rujukan PCare di VClaim");
        btnCekRujukanPCareBPJS.setIconTextGap(0);
        btnCekRujukanPCareBPJS.setName("btnCekRujukanPCareBPJS"); // NOI18N
        btnCekRujukanPCareBPJS.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekRujukanPCareBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekRujukanPCareBPJSActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekRujukanPCareBPJS);

        btnCekRujukanRSBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekRujukanRSBPJS.setText("Cek Rujukan RS di VClaim");
        btnCekRujukanRSBPJS.setToolTipText("");
        btnCekRujukanRSBPJS.setIconTextGap(0);
        btnCekRujukanRSBPJS.setName("btnCekRujukanRSBPJS"); // NOI18N
        btnCekRujukanRSBPJS.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekRujukanRSBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekRujukanRSBPJSActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekRujukanRSBPJS);

        btnCekSuratKontrolBPJS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/vclaim.png"))); // NOI18N
        btnCekSuratKontrolBPJS.setText("Cek Surat Kontrol RS di VClaim");
        btnCekSuratKontrolBPJS.setIconTextGap(0);
        btnCekSuratKontrolBPJS.setName("btnCekSuratKontrolBPJS"); // NOI18N
        btnCekSuratKontrolBPJS.setPreferredSize(new java.awt.Dimension(200, 90));
        btnCekSuratKontrolBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekSuratKontrolBPJSActionPerformed(evt);
            }
        });
        panelGlass7.add(btnCekSuratKontrolBPJS);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void btnCekRujukanPCareBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekRujukanPCareBPJSActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        BPJSCekNoRujukanPCare form = new BPJSCekNoRujukanPCare(null, false);
        form.isCek();
        form.SetRujukan(noRujukan);
        form.setSize(lebar, tinggi);
        form.setLocationRelativeTo(internalFrame1);
        this.dispose();
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnCekRujukanPCareBPJSActionPerformed

    private void btnCekRujukanRSBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekRujukanRSBPJSActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        BPJSCekNoRujukanRS form = new BPJSCekNoRujukanRS(null, false);
        form.isCek();
        form.SetRujukan(noRujukan);
        form.setSize(lebar, tinggi);
        form.setLocationRelativeTo(internalFrame1);
        this.dispose();
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnCekRujukanRSBPJSActionPerformed

    private void btnCekSuratKontrolBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekSuratKontrolBPJSActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        BPJSCekSKDP form = new BPJSCekSKDP(null, false);
        form.isCek();
        form.tampil(noRujukan);
        form.setSize(lebar, tinggi);
        form.setLocationRelativeTo(internalFrame1);
        this.dispose();
        form.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnCekSuratKontrolBPJSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            PilihanBridgingAsuransi2 dialog = new PilihanBridgingAsuransi2(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.ButtonBig btnCekRujukanPCareBPJS;
    private widget.ButtonBig btnCekRujukanRSBPJS;
    private widget.ButtonBig btnCekSuratKontrolBPJS;
    private widget.InternalFrame internalFrame1;
    private widget.panelisi panelGlass6;
    private widget.panelisi panelGlass7;
    // End of variables declaration//GEN-END:variables

    public void setTinggi(int tinggi) {
        this.tinggi = tinggi;
    }

    public void setLebar(int lebar) {
        this.lebar = lebar;
    }

    public void setNoRujukan(String noRujukan) {
        this.noRujukan = noRujukan;
    }

    public void isCek() {

    }
}
